import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import styles from "../case-study.module.css";
const title = "Protection Nuisibles : site, SEO local & acquisition | CODE-V";
const description = "Découvrez comment CODE-V a accompagné Protection Nuisibles à Perpignan : site web, fiche Google, Local Services, Google Ads et visibilité locale.";
export const metadata: Metadata = { title, description, alternates: { canonical: "https://www.code-v.fr/realisations/protection-nuisibles" }, robots: { index: true, follow: true }, openGraph: { title, description, url: "https://www.code-v.fr/realisations/protection-nuisibles", type: "website", locale: "fr_FR" } };
export default function Page(){return <div className={styles.page}>
<header className={styles.hero}><div className="container"><Breadcrumb currentPath="/realisations/protection-nuisibles" items={[{label:"Accueil",href:"/"},{label:"Réalisations",href:"/realisations"},{label:"Protection Nuisibles"}]} /><p className={styles.eyebrow}>PERPIGNAN ET ALENTOURS · ACQUISITION LOCALE</p><h1>Protection Nuisibles.<br /><em>Construire dès le lancement.</em></h1><p className={styles.lead}>CODE-V a accompagné l’entreprise dès sa création pour construire sa présence digitale, sa visibilité locale et ses premiers leviers d’acquisition.</p><ol className={styles.flow}>{["Site","Présence Google","Local Services","Google Ads","Suivi"].map(item=><li key={item}>{item}</li>)}</ol></div></header>
<section className={styles.section}><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>LE POINT DE DÉPART</p><h2>De zéro à une présence locale structurée.</h2></div><div><p>Protection Nuisibles démarrait son activité à Perpignan et alentours. L’entreprise n’avait ni site, ni fiche Google Business Profile, ni campagne d’acquisition, et aucun client au démarrage.</p><p>Il fallait construire une présence crédible et accessible localement, puis mettre en place les moyens de recevoir des demandes. CODE-V a pris en charge l’ensemble de cette présence digitale.</p></div></Reveal></section>
<section className={styles.dark}><div className="container"><Reveal><p className={styles.eyebrow}>LES FONDATIONS WEB</p><h2>Un site pour présenter l’activité<br />et faciliter le contact.</h2><p>CODE-V a créé le site protection-nuisibles.fr. Il présente les services de lutte contre les nuisibles, la zone d’intervention et les points de contact : téléphone et demande de devis.</p></Reveal><figure className={styles.media}><Image unoptimized src="/projects/protection-nuisibles/home.webp" alt="Accueil réel de Protection Nuisibles : services de traitement des nuisibles et demande de devis." width={1440} height={1000} sizes="(max-width: 1200px) 100vw, 1180px" /><figcaption>Page d’accueil du site public, capture du 4 octobre 2026.</figcaption></figure><Link href="/creation-site" className={styles.link}>Découvrir la création de site</Link></div></section>
<section className={styles.section}><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>GOOGLE BUSINESS PROFILE</p><h2>Créer un point de présence locale.</h2></div><div><p>CODE-V a créé la fiche Google Business Profile de l’entreprise. Cette présence complète le site et inscrit l’activité dans les parcours de recherche locale sur Google et Maps.</p><p>Le site présente les services ; la fiche constitue un autre point d’entrée pour découvrir l’entreprise dans son environnement local.</p><Link href="/referencement-local" className={styles.link}>Découvrir le référencement local</Link></div></Reveal></section>
<section className={styles.dark}><div className="container"><p className={styles.eyebrow}>L’ACQUISITION</p><h2>Relier la présence<br /><em>à la demande locale.</em></h2><div className={styles.columns}><div><h3>Google Local Services</h3><p>CODE-V a mis en place Google Local Services et créé les annonces. Ce levier complète la présence locale avec un dispositif publicitaire consacré aux services.</p></div><div><h3>Google Ads</h3><p>CODE-V a également mis en place Google Ads, puis assuré la gestion des campagnes. Le site et les annonces constituent deux parties du même parcours : découvrir une offre locale et pouvoir contacter l’entreprise.</p></div></div><Link href="/publicite" className={styles.link}>Explorer la publicité Google</Link></div></section>
<section className={styles.section}><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>ENVIRON DEUX ANS D’ACCOMPAGNEMENT</p><h2>La mise en place,<br />puis le suivi.</h2></div><div><p>L’accompagnement se poursuit dans la durée : gestion de la présence digitale, suivi de l’acquisition et ajustements. Il relie le site, la fiche Google, Local Services et Google Ads au lieu de traiter chaque outil isolément.</p><p>Ce projet illustre une démarche de lancement suivie : construire les fondations, activer les leviers locaux et accompagner leur fonctionnement.</p><Link href="/solutions" className={styles.link}>Découvrir les solutions CODE-V</Link></div></Reveal></section>
<section className={styles.section}><div className="container"><p className={styles.eyebrow}>UNE VISIBILITÉ OBSERVÉE</p><h2>La présence locale, en situation.</h2><p>Protection Nuisibles apparaît dans le top 3 local Google sur la requête « nuisibles perpignan » au moment de la capture.</p><p>La capture affiche une note de 5,0/5 et 427 avis pour Protection Nuisibles.</p><figure className={`${styles.media} ${styles.evidence}`}><a href="/projects/protection-nuisibles/google-local-pack.webp" className={styles.link} aria-label="Afficher la capture Google originale en grand"><Image unoptimized src="/projects/protection-nuisibles/google-local-pack.webp" alt="Protection Nuisibles apparaît dans le top 3 local Google sur la requête « nuisibles perpignan » au moment de la capture." width={995} height={837} sizes="(max-width: 800px) calc(100vw - 36px), 995px" /></a><figcaption>Protection Nuisibles apparaît dans le top 3 local Google sur la requête « nuisibles perpignan » au moment de la capture.<br />Le classement local peut varier selon la localisation, l’appareil et le moment.</figcaption></figure></div></section>
<section className={styles.final}><div className="container"><h2>Construire votre acquisition locale<br /><em>dès le départ.</em></h2><p>Parlons de votre activité, de votre zone et des leviers à mettre en place.</p><div className={styles.actions}><Link href="/contact?service=digital-strategy" className="button button-primary">Parler de votre projet</Link><Link href="/referencement-local" className={styles.link}>Découvrir le référencement local</Link><Link href="/realisations" className={styles.link}>Voir les réalisations</Link></div></div></section></div>}

