import ReviewsSection from "@/components/ReviewsSection";
import { getReviewsByIds } from "@/data/reviews";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import ChatTrigger from "@/components/RobotAssistant/ChatTrigger";
import NarrativeFilm from "@/components/media/NarrativeFilm";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import { getPublishedProjects } from "@/data/projects";
import { getResourcesByService } from "@/data/resources";
import styles from "./page.module.css";
import { defaultShareImages, getFilmSchema, jsonLd } from "@/lib/seo";

const canonical = "https://www.code-v.fr/creation-site";
const title = "Création de site internet professionnel & refonte | CODE-V";
const description = "CODE-V conçoit et refond des sites professionnels : contenus clairs, parcours de contact, expérience mobile et bases SEO. Découvrez nos réalisations et parlons de votre projet.";
export const metadata: Metadata = {
  title, description, alternates: { canonical },
  openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR", images: defaultShareImages },
};
const serviceSchema = { "@context": "https://schema.org", "@type": "Service", name: "Création et refonte de sites internet professionnels", serviceType: "Création de site internet", description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
const faq = [
  ["Quel budget prévoir pour un site professionnel ?", "Le budget dépend du nombre de pages, des contenus disponibles, des fonctions et des intégrations. Nous précisons ces éléments avant de proposer un devis. Aucun tarif standard ne remplace ce cadrage."],
  ["Combien de temps prend la création d’un site ?", "Le calendrier dépend du périmètre, de la disponibilité des contenus et des validations. Les étapes et responsabilités sont convenues avant le démarrage ; aucun délai universel n’est annoncé."],
  ["Pouvez-vous refondre un site existant ?", "Oui. Nous commençons par examiner le site, ses contenus, les accès et les contraintes. Les URL à conserver, les éventuelles redirections et la migration sont cadrées avant la mise en ligne. Un changement de site ne garantit pas le maintien de tous les classements."],
  ["Le référencement est-il inclus ?", "Les bases techniques et la structure des pages sont définies dans le périmètre du site. Une stratégie SEO continue, la production régulière de contenus et les campagnes publicitaires constituent des accompagnements distincts. Aucun classement Google n’est garanti."],
  ["Qui fournit les textes, les images et les accès ?", "Nous déterminons ensemble ce qui existe et ce qui doit être produit. Vous devez pouvoir autoriser l’usage des contenus et fournir les accès nécessaires. La rédaction, les prises de vue et la production de médias ne sont pas incluses automatiquement."],
  ["L’hébergement et la maintenance sont-ils compris ?", "Leur périmètre est précisé séparément au devis : hébergement, mises à jour, support et évolutions ont des responsabilités propres. Ils ne sont pas automatiquement inclus dans la création du site."],
];

const film = { src: "/videos/creation-site.mp4", poster: "/videos/creation-site-poster.webp", title: "Ce qu’un site professionnel doit faire", description: "Des éléments dispersés se rangent dans une grille et forment un site clair : navigation, promesse, offre, preuve et bouton d’action. Le site passe en version mobile, ses contenus sont structurés et il remonte dans une recherche. Un visiteur parcourt la page, voit une preuve, touche le bouton et envoie une demande. La demande rejoint ensuite le contact, le CRM, le suivi et l’automatisation. Le film se termine sur le logo CODE-V : des sites pensés pour agir." };
// uploadDate: merge of the film on master (PR #4, 541f15b), i.e. its publication on the site.
const filmSchema = getFilmSchema({ name: film.title, description: film.description, src: film.src, poster: film.poster, uploadDate: "2026-10-08T14:51:03+02:00", duration: "PT20S" });
export default function CreationSitePage() {
  const projects = getPublishedProjects();
  const chateau = projects.find(project => project.id === "chateau-de-projan");
  const painter = projects.find(project => project.id === "peinture-occitane");
  const pest = projects.find(project => project.id === "express-nuisibles");
  // Price/refonte/format briefs appear here only when actually published.
  const resources = getResourcesByService("website");
  return <div className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(filmSchema) }} />
    <section className={styles.hero} aria-labelledby="website-title"><div className="container"><Breadcrumb {...getPageBreadcrumb("/creation-site")} />
      <div className={styles.heroGrid}><div><p className={styles.eyebrow}>CRÉATION & REFONTE / CODE-V</p><h1 id="website-title">Un site professionnel.<br /><em>Un chemin vers vous.</em></h1><p className={styles.lead}>Nous créons des sites internet qui présentent clairement votre activité et facilitent la prise de contact. Un site vitrine ou une refonte, construit autour de ce que vos visiteurs doivent comprendre et pouvoir faire.</p><div className={styles.actions}><Link href="/contact?service=website" className="button button-primary">Parler de votre projet <span aria-hidden="true">↗</span></Link><a href="#realisations" className={styles.textLink}>Voir le travail réalisé <span aria-hidden="true">↓</span></a></div><p className={styles.note}>Périmètre, contenus et budget définis ensemble, sur devis.</p></div>
      {chateau?.coverImage && <Reveal className={styles.heroMedia}><figure><Image src={chateau.coverImage.src} alt={chateau.coverImage.alt} width={chateau.coverImage.width} height={chateau.coverImage.height} sizes="(max-width: 900px) calc(100vw - 36px), (max-width: 1260px) 46vw, 550px" priority /><figcaption><span>UNE RÉALISATION CODE-V</span><strong>{chateau.name}</strong><Link href="/realisations#selection">Découvrir ce site <span aria-hidden="true">↗</span></Link></figcaption></figure></Reveal>}
      </div>
    </div></section>

    <section className={styles.needs} aria-labelledby="needs-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>CE QUI DOIT CHANGER</p><h2 id="needs-title">Votre activité est claire.<br /><span>Votre site l’est-il aussi ?</span></h2><p>Un site peut exister sans expliquer votre offre, rassurer sur votre travail ou rendre le contact évident. La création comme la refonte commence par ce constat.</p></Reveal><Reveal className={styles.needList}><div><h3>On ne comprend pas ce que vous proposez.</h3><p>Nous hiérarchisons les services, les contenus et les preuves pour rendre votre proposition lisible.</p></div><div><h3>Le contact se perd dans la navigation.</h3><p>Les actions attendues deviennent visibles : appeler, expliquer un besoin ou envoyer une demande.</p></div><div><h3>Le site est difficile à utiliser sur mobile.</h3><p>La composition, la lecture et les formulaires sont pensés pour les petits écrans, puis vérifiés.</p></div></Reveal></div></section>

    <section className={styles.film} aria-labelledby="film-title"><div className="container"><Reveal className={styles.filmHead}><p className={styles.eyebrow}>EN MOUVEMENT / 20 SECONDES</p><h2 id="film-title">Une présence en ligne.<br /><span>Ou un outil qui travaille.</span></h2></Reveal></div>
      <div className={styles.filmStage}><NarrativeFilm src={film.src} srcSmall="/videos/creation-site-720.mp4" poster={film.poster} width={1920} height={1080} title={film.title} description={film.description} /></div>
    </section>

    <section className={styles.formats} aria-labelledby="formats-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>LE BON PÉRIMÈTRE</p><h2 id="formats-title">Créer une présence.<br /><span>Ou lui donner une nouvelle direction.</span></h2></Reveal><div className={styles.formatRows}>
      <Reveal><article><h3>Un site vitrine pour présenter votre entreprise.</h3><div><p>Vos services, votre manière de travailler et vos informations de contact. Une structure adaptée à un artisan, une entreprise de services ou un établissement.</p><p className={styles.note}>Pages et fonctionnalités précisées selon votre activité.</p></div></article></Reveal>
      <Reveal><article><h3>Un site de présentation avec des contenus spécifiques.</h3><div><p>Une carte, des espaces, une sélection de produits ou des réalisations : nous organisons ce qui aide votre public à se projeter.</p><p className={styles.note}>Un catalogue de présentation n’est pas une boutique avec paiement ; les fonctions avancées nécessitent un cadrage.</p></div></article></Reveal>
      <Reveal><article><h3>Une refonte qui part de votre site actuel.</h3><div><p>Clarifier les contenus, revoir les parcours et améliorer l’usage. Nous examinons ce qui mérite d’être conservé et les contraintes de migration.</p><p className={styles.note}>La préservation des URL et les redirections éventuelles sont définies au périmètre, sans promesse de classement.</p></div></article></Reveal>
    </div><Link href="/solutions/web-applications" className={styles.textLink}>Besoin d’une boutique ou d’une application ? Explorer les formats web <span aria-hidden="true">↗</span></Link></div></section>

    <section className={styles.approach} aria-labelledby="approach-title"><div className={`container ${styles.approachGrid}`}><Reveal><p className={styles.eyebrow}>L’APPROCHE CODE-V</p><h2 id="approach-title">Le design attire.<br /><em>Le parcours donne une suite.</em></h2><p>Nous relions le message, les preuves et l’action attendue. L’objectif est de faciliter une demande pertinente, sans promettre un nombre de prospects.</p><ChatTrigger intent="website" className="button button-primary">Décrire votre besoin</ChatTrigger></Reveal><div className={styles.principles}>
      <Reveal><div><h3>Des contenus qui vont à l’essentiel.</h3><p>Une offre compréhensible, des réalisations réelles et les informations nécessaires pour décider de vous contacter.</p></div></Reveal>
      <Reveal><div><h3>Une expérience utilisable.</h3><p>Hiérarchie, contraste, clavier et formulaires : l’UX se vérifie dans le parcours, pas seulement dans une maquette.</p></div></Reveal>
      <Reveal><div><h3>Des bases techniques et SEO.</h3><p>Structure de titres, métadonnées, liens et images adaptés. La performance est contrôlée sur le périmètre réalisé ; le référencement continu reste un accompagnement distinct.</p><Link href="/referencement" className={styles.textLink}>Comprendre l’accompagnement SEO <span aria-hidden="true">↗</span></Link></div></Reveal>
      <Reveal><div><h3>Un point de contact visible.</h3><p>Des CTA placés au bon moment et un formulaire compréhensible. Le suivi avancé des conversions et les tests A/B ne sont pas inclus automatiquement.</p></div></Reveal>
    </div></div></section>

    <section id="realisations" className={styles.proof} aria-labelledby="proof-title"><div className="container"><Reveal className={styles.proofHeading}><div><p className={styles.eyebrow}>DES SITES RÉELS</p><h2 id="proof-title">Des métiers différents.<br /><span>Une présence à leur image.</span></h2></div><p>Le site d’un domaine, celui d’un artisan ou d’un service local n’ont pas les mêmes contenus. Découvrez des réalisations CODE-V à travers leurs sites et leurs captures publiques.</p></Reveal>
      <div className={styles.projectComposition}>{painter?.coverImage && <Reveal className={styles.painter}><figure><Image src={painter.coverImage.src} alt={painter.coverImage.alt} width={painter.coverImage.width} height={painter.coverImage.height} sizes="(max-width: 900px) calc(100vw - 36px), 650px" /><figcaption><h3>{painter.name}</h3><p>Présenter les prestations de peinture et de rénovation, et proposer un accès au devis.</p><Link href="/realisations#peinture-occitane" className={styles.textLink}>Voir cette réalisation <span aria-hidden="true">↗</span></Link></figcaption></figure></Reveal>}{pest?.coverImage && <Reveal className={styles.pest}><figure><Image src={pest.coverImage.src} alt={pest.coverImage.alt} width={pest.coverImage.width} height={pest.coverImage.height} sizes="(max-width: 900px) calc(100vw - 36px), 440px" /><figcaption><h3>{pest.name}</h3><p>Expliquer les traitements et les zones d’intervention, avec un formulaire de demande visible.</p><Link href="/realisations#express-nuisibles" className={styles.textLink}>Voir cette réalisation <span aria-hidden="true">↗</span></Link></figcaption></figure></Reveal>}</div>
      <Link href="/realisations" className={styles.textLink}>Voir les réalisations CODE-V <span aria-hidden="true">↗</span></Link>
    </div></section>

    <ReviewsSection reviews={getReviewsByIds(["gaston-barreau", "jeremie-lagrange", "pierre-louis"])} heading="Un site, une expérience partagée." variant="featured" maxItems={3} compact />    <section className={styles.method} aria-labelledby="method-title"><div className="container"><Reveal className={styles.split}><div><p className={styles.eyebrow}>DU BESOIN À LA MISE EN LIGNE</p><h2 id="method-title">Un projet cadré.<br /><span>Des choix discutés.</span></h2></div><p>Vous savez ce qui doit être préparé, ce qui sera réalisé et ce qui nécessite votre validation. Le calendrier et le nombre d’échanges sont convenus selon le projet.</p></Reveal><div className={styles.methodLine}>{[["Cadrer", "Votre activité, vos publics, les pages et les actions attendues."], ["Concevoir", "L’arborescence, les contenus et la direction visuelle à valider."], ["Construire", "Le développement, l’intégration des contenus et les fonctions convenues."], ["Vérifier", "Mobile, clavier, liens et parcours de contact avant la mise en ligne."]].map(([name, text]) => <Reveal key={name}><div><h3>{name}</h3><p>{text}</p></div></Reveal>)}</div></div></section>

    <section className={styles.scope} aria-labelledby="scope-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>CE QUE NOUS CADRONS ENSEMBLE</p><h2 id="scope-title">Un devis lisible.<br /><span>Un périmètre explicite.</span></h2><p>Pages, fonctions, contenus, validations et accès sont précisés avant le démarrage. La rédaction, les médias, l’hébergement et la maintenance ne sont pas ajoutés implicitement à la création.</p><p>Les technologies sont choisies selon les usages et les contraintes. Le site CODE-V utilise Next.js, React et TypeScript ; cela ne préjuge pas de la solution adaptée à votre entreprise.</p><Link href="/maintenance-site" className={styles.textLink}>Découvrir la maintenance après mise en ligne <span aria-hidden="true">↗</span></Link><Link href="/contact?service=website" className={styles.textLink}>Préciser le périmètre de mon site <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.scopeNote}><h3>Pour commencer, quelques éléments suffisent.</h3><p>Votre activité, l’adresse de votre site s’il existe, ce que vous souhaitez changer et les contenus dont vous disposez. Nous vous aidons ensuite à préciser le besoin.</p><p className={styles.note}>Le nombre de pages, les intégrations et les responsabilités de chacun seront définis au devis. Une stratégie d’acquisition peut compléter le site ; elle constitue un périmètre distinct.</p></Reveal></div></section>

    <section className={styles.faq} aria-labelledby="faq-title"><div className={`container ${styles.faqGrid}`}><Reveal><p className={styles.eyebrow}>AVANT DE SE LANCER</p><h2 id="faq-title">Les questions<br /><span>qui cadrent le projet.</span></h2></Reveal><div>{faq.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    {resources.length > 0 && <section className={styles.resources} aria-labelledby="reading-title"><div className="container"><h2 id="reading-title">Pour préparer votre projet</h2>{resources.map(resource => <Link key={resource.id} className={styles.textLink} href={`/ressources/${resource.slug}`}>{resource.title} <span aria-hidden="true">↗</span></Link>)}</div></section>}

    <section className={styles.final} aria-labelledby="final-title"><Reveal className="container"><p className={styles.eyebrow}>CRÉATION OU REFONTE</p><h2 id="final-title">Votre activité.<br /><em>Son prochain site.</em></h2><p>Expliquez-nous ce que votre site doit présenter et faciliter. Nous cadrerons la suite à partir de votre situation.</p><Link href="/contact?service=website" className="button button-primary">Parler de votre projet <span aria-hidden="true">↗</span></Link><Link href="/ressources" className={styles.textLink}>Explorer les repères CODE-V <span aria-hidden="true">↗</span></Link></Reveal></section>
  </div>;
}
