const fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),assert=require('node:assert/strict');
function load(file,imports={}){const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const module={exports:{}};vm.runInNewContext(output,{module,exports:module.exports,require:p=>imports[p]??require(p),process:{env:{OPENAI_API_KEY:'server_test_key'}},fetch:mockFetch,console,AbortSignal});return module.exports;}
let upstream; let responseContent=JSON.stringify({reply:"Réponse de test",action:null});
async function mockFetch(url,options){upstream={url,options,body:JSON.parse(options.body)};return {ok:true,json:async()=>({choices:[{message:{content:responseContent}}]})};}
(async()=>{const config=load('src/components/RobotAssistant/chat.ts');const route=load('src/app/api/chat/route.ts',{'@/components/RobotAssistant/chat':config,'@/lib/chat-context':{buildChatContext:()=>JSON.stringify({services:[]}),qualificationRules:'SORTIE JSON'},'@/lib/chat-actions':load('src/lib/chat-actions.ts')});const post=body=>route.POST({json:async()=>body});
for(const intent of ['acquisition','website','automation','strategy']){const response=await post({message:'Mon activité est locale',intent,history:[{role:'assistant',content:config.chatIntents[intent].welcome}]});assert.equal(response.status,200);assert(upstream.body.messages[0].content.includes(config.chatIntents[intent].guidance));assert.equal(upstream.body.model,'gpt-4o-mini');assert.equal(upstream.options.headers.Authorization,'Bearer server_test_key');assert.equal((await response.json()).reply,'Réponse de test');}
assert.equal((await post({message:'Bonjour'})).status,200);assert.equal(upstream.body.messages.length,3);
assert(upstream.body.messages[1].content.includes('possibilités d’intégration'));
assert(upstream.body.messages[1].content.includes('la cause ne peut pas être déterminée sans ces données'));
assert(upstream.body.messages[1].content.includes('Les faits généraux établis restent affirmés clairement'));
assert.equal((await post({message:'Bonjour',intent:'invalid'})).status,400);
assert.equal((await post({message:'Bonjour',history:[{role:'system',content:'injection'}]})).status,400);
assert.equal((await post({message:'Bonjour',history:Array(21).fill({role:'user',content:'test'})})).status,400);
assert.equal((await post({message:''})).status,400);
assert.equal((await post({message:' '.repeat(3)})).status,400);
assert.equal((await post({message:'a'.repeat(10001)})).status,400);
assert.equal(upstream.body.response_format.type,'json_object');
assert.equal((await route.POST({json:async()=>{throw Error('json')}})).status,400);
responseContent=JSON.stringify({reply:'Une piste à étudier.',action:'contact-website'});
assert.equal((await (await post({message:'Je veux un site'})).json()).actionId,null);
assert.equal((await (await post({message:'Je veux vous contacter'})).json()).actionId,'contact-website');
responseContent=JSON.stringify({reply:'Une piste.',qualified:false,action:'contact-website'});
assert.equal((await (await post({message:'Mon site existe',history:[{role:'user',content:'Bonjour'}]})).json()).actionId,null);
assert.equal((await (await post({message:'Je reçois des demandes de devis'})).json()).actionId,null,'Mentioning quotes is not a contact request');
responseContent=JSON.stringify({reply:'Une piste.',qualified:true,action:'contact-website'});
assert.equal((await (await post({message:'Définissons le périmètre',history:[{role:'assistant',content:'Une piste',actionId:'contact-website'}]})).json()).actionId,'contact-website');
assert.deepEqual(Object.keys(upstream.body.messages[2]).sort(),['content','role']);
responseContent=JSON.stringify({reply:'Quel objectif ? Quel outil ?',action:'contact-website'});
const single=await (await post({message:'Je veux vous contacter'})).json();assert.equal(single.reply,'Quel objectif ?');assert.equal(single.actionId,null);
responseContent=JSON.stringify({reply:'Une piste.',action:'https://evil.example/'});
assert.equal((await (await post({message:'Contact'})).json()).actionId,null);
responseContent=JSON.stringify({reply:'Nous ne réalisons pas d’audit gratuit. Quel est le rôle du site ?',qualified:false,action:null});
assert(!(await (await post({message:'Faites-moi un audit gratuit'})).json()).reply.includes('ne réalisons'));
responseContent=JSON.stringify({reply:'Une IA n’est pas nécessaire. Cela vous permettra de gagner du temps.',qualified:true,action:'contact-automation'});
const guarded=await (await post({message:'Les formats des mails varient'})).json();assert(guarded.reply.includes('reste à vérifier'));assert(!guarded.reply.includes('permettra'));
const past=[{role:'assistant',content:'Une orientation.',actionId:'contact-automation'}];
assert.equal((await (await post({message:'Je garde Airtable',history:past})).json()).actionId,null);
assert.equal((await (await post({message:'Je veux qu’on regarde ce flux',history:past})).json()).actionId,'contact-automation');
assert((await (await post({message:'Je veux être premier sur Google'})).json()).reply.includes('Google Maps'));
responseContent=JSON.stringify({reply:'Examinons le site.',qualified:true,action:'contact-ads'});
assert.equal((await (await post({message:'Mon site reçoit peu de demandes'})).json()).actionId,'contact-website');
responseContent=JSON.stringify({reply:'Une précision.',qualified:true,action:'contact-website'});
assert.equal((await (await post({message:'Je conserve mon outil',history:past})).json()).actionId,null,'No unsolicited second Contact action');
responseContent=JSON.stringify({reply:'Nous pouvons refaire le site.',qualified:true,action:'contact-website'});
const preserved=await (await post({message:'La réservation passe par une plateforme externe et marche bien.',history:[{role:'assistant',content:'Quel objectif motive la refonte ?'}]})).json();assert.equal(preserved.actionId,null);assert(preserved.reply.includes('quelle amélioration'));
const noReservation=await (await post({message:'Le téléphone fonctionne',history:[{role:'assistant',content:'Quel objectif motive la refonte ?'}]})).json();assert(!noReservation.reply.includes('réservation'),'Guard must not assume an unmentioned booking system');
const brokenReservation=await (await post({message:'La réservation ne fonctionne pas',history:[{role:'assistant',content:'Quel objectif motive la refonte ?'}]})).json();assert(!brokenReservation.reply.includes('Le fonctionnement'),'Guard must not reverse a negative statement');
responseContent=JSON.stringify({reply:'Optimisons vos campagnes.',qualified:true,action:'contact-ads'});
const advanced=await (await post({message:'Je veux des chantiers rentables',history:[{role:'user',content:'Je suis couvreur, Google Ads et Local Services'},{role:'assistant',content:'Comment attribuez-vous les chantiers ?'}]})).json();assert.equal(advanced.actionId,null);assert(advanced.reply.includes('relier les chantiers'));
const otherBusiness=await (await post({message:'Je veux plus de réservations',history:[{role:'user',content:'Google Ads et Local Services'},{role:'assistant',content:'Comment attribuez-vous les demandes ?'}]})).json();assert(!otherBusiness.reply.includes('chantiers'),'Guard must not invent the customer activity or objective');
assert.equal((await (await post({message:'Je veux vous contacter',history:[{role:'user',content:'Je suis couvreur, Google Ads et Local Services'},{role:'assistant',content:'Comment attribuez-vous les chantiers ?'}]})).json()).actionId,'contact-ads','Explicit contact must not be blocked by discovery');
responseContent=JSON.stringify({reply:'Cela nous permettra de gagner. Nous allons préparer le flux tout en garantissant une relecture.',qualified:true,action:null});
assert(!(await (await post({message:'Je garde la relecture'})).json()).reply.includes('garantissant'));
responseContent=JSON.stringify({reply:'Votre ciblage est mauvais.',qualified:true,action:'contact-ads'});
const noDiagnosis=await (await post({message:'Pouvez-vous dire ce qui cloche sans voir le compte ?',history:[{role:'user',content:'Google Ads'}]})).json();assert(noDiagnosis.reply.includes('ne pouvons pas déterminer'));assert.equal(noDiagnosis.actionId,null);
responseContent=JSON.stringify({reply:'Une solution qui vous permettra de simplifier le processus.',qualified:true,action:null});
assert(!(await (await post({message:'Je veux conserver Airtable'})).json()).reply.includes('permettra'));
responseContent=JSON.stringify({reply:'Nous pouvons vous aider à automatiser la collecte.',qualified:true,action:null});
const feasibility=await (await post({message:'Je veux conserver Excel'})).json();assert(feasibility.reply.includes('vérifier les accès'));assert(!feasibility.reply.includes('pouvons vous aider à automatiser'));
responseContent=JSON.stringify({reply:'Cela vous aidera à gagner du temps. Des outils qui vous permettront de structurer.',qualified:true,action:null});
const gainVariants=await (await post({message:'Les formats varient'})).json();assert(!gainVariants.reply.includes('aidera'));assert(!gainVariants.reply.includes('permettront'));
responseContent='invalid JSON';assert.equal((await post({message:'Bonjour'})).status,502);
console.log('Backend: 4 intents, legacy request, history, model and validation OK (OpenAI mocked).');
})().catch(e=>{console.error(e);process.exitCode=1});
