const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),ts=require('typescript');
const cache={};let sent,fail=false;
const env={RESEND_API_KEY:'test-key-private',CONTACT_EMAIL:'contact@example.test',RESEND_FROM:'CODE-V <hello@example.test>'};
function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{exports:m.exports,require:n=>{if(n==='next/server')return {NextResponse:{json:(data,init)=>({data,status:init?.status||200})}};if(n==='resend')return {Resend: function(){this.batch={send:async items=>{sent=items;return fail?{error:{message:'test-key-private'}}:{data:{data:[{id:'1'},{id:'2'}]}}}}}};return load(n.startsWith('@/')?'src/'+n.slice(2)+'.ts':path.join(path.dirname(file),n+'.ts'))},process:{env},URL,Intl,Date});return m.exports}
const client=load('src/emails/ContactConfirmationEmail.ts').ContactConfirmationEmail,internal=load('src/emails/NewContactEmail.ts').NewContactEmail;
const full={name:'Adrien Exemple',email:'prospect@example.test',service:'Création de site',company:'Entreprise & associés',phone:'+33 6 12 34 56 78',source:'/contact',message:'Bonjour <script>alert("test")</script>\n'+('Un projet à préciser. '.repeat(90)),receivedAt:new Date('2026-10-04T10:00:00Z')};
for(const render of [client,internal]){const e=render(full);assert(e.html.includes('&lt;script&gt;'));assert(!e.html.includes('<script>'));assert(e.text.includes(full.message));assert(e.html.includes('https://www.code-v.fr/brand/code-v-logo-email.png'));assert(!e.html.includes('font-face'));assert(!e.html.includes('test-key-private'));}
assert(client(full).html.includes('Merci Adrien.'));assert(internal(full).html.includes('mailto:prospect%40example.test'));assert(internal(full).html.includes('tel:+33612345678'));
const minimal={name:'Camille',email:'camille@example.test',message:'Mon projet.',receivedAt:full.receivedAt};
for(const e of [client(minimal),internal(minimal)])assert(!/Société|Téléphone|Page \/ source|champ non fourni|undefined/.test(e.html));assert(!client(minimal).html.includes('>Service<'));
const out='docs/email-previews';fs.mkdirSync(out,{recursive:true});for(const [file,email] of [['confirmation',client(full)],['nouveau-contact',internal(full)],['confirmation-minimale',client(minimal)],['contact-minimal',internal(minimal)]]){fs.writeFileSync(out+'/'+file+'.html',email.html);fs.writeFileSync(out+'/'+file+'.txt',email.text)}
(async()=>{const post=load('src/app/api/contact/route.ts').POST;const req=x=>({json:async()=>x});
assert.equal((await post(req(full))).status,200);assert.equal(sent.length,2);assert.equal(sent[0].replyTo,full.email);assert.equal(sent[1].replyTo,env.CONTACT_EMAIL);assert.equal(sent[0].from,env.RESEND_FROM);assert(sent.every(e=>e.html&&e.text));fail=true;const err=await post(req(full));assert.equal(err.status,503);assert(!JSON.stringify(err).includes('test-key-private'));fail=false;delete env.RESEND_API_KEY;assert.equal((await post(req(full))).status,503);assert.equal((await post(req({...full,email:'x\ny@example.test'}))).status,400);console.log('Templates, escaping, optional fields, mailto/tel, both sends/reply-to, safe failures OK; 4 local previews generated');})().catch(e=>{console.error(e);process.exit(1)});
