import ResourceReadings from "@/components/resources/ResourceReadings";
import ReviewsSection from "@/components/ReviewsSection";
import { getReviewsByIds } from "@/data/reviews";
import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import styles from "./page.module.css";

const canonical = "https://www.code-v.fr/publicite";
const title = "Google Ads & acquisition payante | CODE-V";
const description = "CODE-V accompagne vos campagnes Google Ads : ciblage Search, pages de destination, suivi des conversions et pilotage du budget. Parlons de votre acquisition.";
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR" } };
const service = { "@context": "https://schema.org", "@type": "Service", name: "Campagnes Google Ads & acquisition payante", serviceType: "Acquisition payante", description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
const questions = [
  ["Google Ads ou SEO ?", "Google Ads permet de diffuser des annonces avec un budget média. Le SEO travaille la présence organique du site dans le temps. Le choix dépend de votre offre, de vos objectifs et de l’existant ; les deux leviers peuvent se compléter."],
  ["Quel budget prévoir ?", "Le budget média dépend des recherches visées, de la concurrence, de votre zone et des objectifs. Il est distinct des honoraires de mise en place et de pilotage. La page de destination, les créations et le tracking sont cadrés séparément si nécessaire. Nous définissons un périmètre sur devis, sans montant standard annoncé."],
  ["Combien de temps avant d’obtenir des données utiles ?", "Cela dépend du volume de diffusion, des interactions et du délai entre visite et contact. Nous vérifions d’abord la mesure puis analysons des périodes pertinentes. Quelques clics ne suffisent pas à conclure ; aucun délai de génération de prospects n’est garanti."],
  ["Faut-il une landing page ?", "Il faut une destination cohérente avec l’annonce et facile à utiliser. Une page existante peut convenir. Une landing page dédiée est pertinente lorsque l’offre ou le parcours exige une réponse plus ciblée ; sa création est définie dans un périmètre distinct."],
  ["Peut-on améliorer une campagne existante ?", "Oui, après accès au compte et examen des objectifs, de la structure, des requêtes, des annonces, des destinations et de la mesure. Nous priorisons les ajustements selon ce que les données permettent de comprendre."],
  ["Comment mesurer les conversions ?", "Nous définissons les actions utiles, comme un formulaire envoyé, puis configurons et testons les événements convenus selon les outils et le cadre de consentement retenus. Les appels et les contacts hors ligne demandent un cadrage spécifique. Une action mesurée ne signifie pas automatiquement un prospect qualifié."],
  ["Google Ads Search ou Local Services Ads ?", "Search repose sur des annonces liées aux recherches et à une destination choisie. Local Services utilise un dispositif distinct de mise en relation pour certaines activités et zones. Sa disponibilité et les vérifications requises sont examinées avant de le proposer."],
  ["Meta Ads est-il pertinent pour mon activité ?", "Facebook et Instagram peuvent présenter une offre à une audience qui ne la recherche pas encore, soutenir la notoriété ou recueillir des demandes. Leur pertinence dépend du message, des créations, de l’audience et du traitement des contacts. Le retargeting dépend aussi des audiences utilisables et des paramètres de consentement."],
];
const flow = ["Annonce", "Page", "Action", "Mesure", "Optimisation"];
const method = [
  ["Cadrer", "Offre, cible, zone, budget média et définition d’une demande utile."],
  ["Préparer", "Compte, structure, annonces, destination et vérification de la mesure."],
  ["Diffuser", "Lancement du périmètre convenu et contrôle de la diffusion et des dépenses."],
  ["Ajuster", "Lecture des données, qualité des contacts et prochaines décisions documentées."],
];

export default function PublicitePage() {
  return <div className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(service).replace(/</g, "\u003c") }} />
    <section className={styles.hero} aria-labelledby="ads-title"><div className="container"><Breadcrumb {...getPageBreadcrumb("/publicite")} /><div className={styles.heroGrid}>
      <div><p className={styles.eyebrow}>ACQUISITION PAYANTE / CODE-V</p><h1 id="ads-title">Le bon clic.<br /><em>La suite compte.</em></h1><p className={styles.lead}>Google Ads capte une intention. Votre page doit y répondre, et votre mesure éclairer les décisions. CODE-V relie ces étapes pour piloter votre acquisition autour des demandes utiles.</p><Link href="/contact?service=ads" className="button button-primary">Parler de votre acquisition <span aria-hidden="true">↗</span></Link></div>
      <Reveal className={styles.signal}><figure><div className={styles.query}><span>LE POINT DE DÉPART</span><strong>Une recherche.<br />Un besoin précis.</strong></div><ol className={styles.flow}>{flow.map((label,index) => <li key={label}><span aria-hidden="true">{String(index+1).padStart(2,"0")}</span><strong>{label}</strong></li>)}</ol><figcaption>Une chaîne de décisions, de l’intention à l’optimisation.</figcaption></figure></Reveal>
    </div><nav className={styles.chapterNav} aria-label="Parcours acquisition"><a href="#search">Google Ads Search</a><a href="#conversion">Page & mesure</a><a href="#pilotage">Le pilotage</a><a href="#questions">Vos questions</a></nav></div></section>

    <section className={styles.intro} aria-labelledby="intro-title"><Reveal className={'container '+styles.split}><div><p className={styles.eyebrow}>INVESTIR AVEC UN CAP</p><h2 id="intro-title">La dépense se voit.<br /><span>Le parcours doit se comprendre.</span></h2></div><div><p>Des clics sans contacts, une annonce qui promet autre chose que la page, un formulaire dont le suivi ne fonctionne pas : augmenter le budget ne corrige pas tout.</p><p>Nous commençons par votre offre, les demandes que vous souhaitez recevoir et la capacité de votre équipe à les traiter. Le canal vient ensuite. Le budget média et les honoraires sont séparés pour clarifier ce qui finance la diffusion et ce qui finance le travail.</p></div></Reveal></section>

    <section id="search" className={styles.search} aria-labelledby="search-title"><div className={'container '+styles.split}><Reveal><p className={styles.eyebrow}>LE LEVIER PRINCIPAL : GOOGLE ADS SEARCH</p><h2 id="search-title">Répondre à une recherche.<br /><span>Avec une offre claire.</span></h2><p>Les campagnes Search permettent de présenter une annonce à des personnes qui expriment un besoin. Nous travaillons les recherches pertinentes, la zone, le message et la page qui prend le relais.</p><Link href="/contact?service=ads" className={styles.textLink}>Étudier une campagne <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.searchNotes}><div><h3>Une structure lisible.</h3><p>Des campagnes et groupes d’annonces organisés selon vos services et intentions. Les mots clés et exclusions aident à orienter la diffusion ; les requêtes réellement observées guident les ajustements.</p></div><div><h3>Un message qui prépare la suite.</h3><p>Les annonces présentent l’offre sans décalage avec la destination. Elles doivent aider le visiteur à comprendre ce qu’il trouvera et quelle action il pourra entreprendre.</p></div><div><h3>Un budget qui sert une priorité.</h3><p>Nous définissons les paramètres de diffusion et de dépenses, puis suivons leur évolution. Le budget se pilote avec les données et la qualité des demandes, sans garantir un volume ou un coût par prospect.</p></div></Reveal></div></section>

    <section id="conversion" className={styles.conversion} aria-labelledby="conversion-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>DE L’ANNONCE À LA DEMANDE</p><h2 id="conversion-title">La campagne ouvre la porte.<br /><em>La page fait avancer.</em></h2></Reveal><div className={styles.editorialRow}><Reveal><h3>Une destination.<br />Une action compréhensible.</h3></Reveal><Reveal><p>Une landing page relie le besoin exprimé à votre réponse : offre, éléments concrets, contact. Le message, l’usage mobile et le formulaire doivent faciliter le parcours.</p><p>Nous vérifions si votre page actuelle convient ou si une destination dédiée est nécessaire. La production d’une landing page se cadre séparément du pilotage des annonces.</p><Link href="/creation-site" className={styles.textLink}>Comprendre la création et la refonte de site <span aria-hidden="true">↗</span></Link></Reveal></div><div className={styles.editorialRow}><Reveal><h3>Mesurer une action.<br />Puis sa valeur réelle.</h3></Reveal><Reveal><p>Tracking, événements et conversions doivent décrire les actions utiles. Nous définissons les événements convenus, vérifions leur déclenchement et la cohérence entre le site et les outils publicitaires.</p><p>La mesure est configurée selon vos outils et le cadre de consentement retenu. Formulaires, appels et retours commerciaux n’ont pas le même sens : les contacts qualifiés se distinguent des simples interactions.</p></Reveal></div><Link href="/contact?service=ads" className="button button-primary">Faire le point sur votre dispositif <span aria-hidden="true">↗</span></Link></div></section>

    <section id="pilotage" className={styles.pilotage} aria-labelledby="pilotage-title"><div className={'container '+styles.split}><Reveal><p className={styles.eyebrow}>OPTIMISER AVEC LES FAITS</p><h2 id="pilotage-title">Observer.<br /><span>Décider. Ajuster.</span></h2><p>Requêtes, annonces, destinations, conversions et dépenses sont relues ensemble. Les retours sur les demandes reçues aident à comprendre ce qui sert réellement votre activité.</p></Reveal><Reveal className={styles.observation}><h3>Chaque modification a une raison.</h3><p>Affiner le ciblage, exclure une recherche peu pertinente, travailler le message ou améliorer la page : les actions sont priorisées selon les observations. Nous documentons les changements pour suivre leur effet sur des périodes adaptées.</p><p>La cadence du suivi, les responsabilités et le périmètre de mesure sont convenus avant lancement. Le pilotage ne remplace pas le traitement commercial des demandes.</p></Reveal></div></section>

    <section className={styles.channels} aria-labelledby="channels-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>DES COMPLÉMENTS, SELON LE CONTEXTE</p><h2 id="channels-title">Un canal se choisit.<br /><span>Il ne s’ajoute pas par défaut.</span></h2></Reveal><div className={styles.channelRow}><h3>Local Services Ads</h3><div><p>Un dispositif distinct pour certaines activités de services et zones desservies. Nous vérifions sa disponibilité, l’éligibilité de l’activité et les contrôles demandés avant de le proposer. La gestion des demandes et le budget se cadrent selon ses règles propres.</p><Link href="/referencement-local" className={styles.textLink}>Distinguer publicité et visibilité locale <span aria-hidden="true">↗</span></Link></div></div><div className={styles.channelRow}><h3>Meta Ads</h3><div><p>Facebook et Instagram peuvent faire découvrir une offre avant qu’elle soit recherchée, soutenir la notoriété ou générer des demandes selon le contexte. Les créations et le traitement des contacts jouent un rôle central.</p><p>Le retargeting peut prolonger un intérêt lorsqu’une audience utilisable et les conditions de consentement le permettent. L’animation organique des réseaux et la production de contenus ne sont pas incluses automatiquement.</p></div></div></div></section>

    <ReviewsSection reviews={getReviewsByIds(["olivier-garnier"])} heading="Leur retour sur l’accompagnement." variant="inline" maxItems={1} compact />    <section className={styles.method} aria-labelledby="method-title"><div className="container"><Reveal><p className={styles.eyebrow}>LA MÉTHODE CODE-V</p><h2 id="method-title">Un objectif partagé.<br /><em>Des étapes reliées.</em></h2></Reveal><div className={styles.methodLine}>{method.map(([name,text]) => <Reveal key={name}><h3>{name}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section className={styles.links} aria-labelledby="links-title"><Reveal className={'container '+styles.split}><div><p className={styles.eyebrow}>UN DISPOSITIF COHÉRENT</p><h2 id="links-title">Ads, SEO, site.<br /><span>Des rôles complémentaires.</span></h2></div><div><p>Les annonces diffusent une offre, le SEO travaille la présence organique, le site aide à comprendre et agir. Le choix des leviers dépend de votre situation et du parcours à construire.</p><Link href="/referencement" className={styles.textLink}>Comprendre le référencement naturel <span aria-hidden="true">↗</span></Link><Link href="/solutions" className={styles.textLink}>Voir toutes les solutions <span aria-hidden="true">↗</span></Link><Link href="/realisations" className={styles.textLink}>Découvrir les réalisations web CODE-V <span aria-hidden="true">↗</span></Link><Link href="/ressources" className={styles.textLink}>Explorer les ressources <span aria-hidden="true">↗</span></Link></div></Reveal></section>
    <section id="questions" className={styles.faq} aria-labelledby="faq-title"><div className="container"><Reveal><p className={styles.eyebrow}>AVANT LE LANCEMENT</p><h2 id="faq-title">Vos questions<br /><span>sur l’acquisition payante.</span></h2></Reveal><div className={styles.faqList}>{questions.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
    <section><div className="container"><h2>Deux parcours d’acquisition locale.</h2><p><Link href="/realisations/nuisibles-toulon" className={styles.textLink}>Nuisibles Toulon : site et Google Ads</Link></p><p><Link href="/realisations/protection-nuisibles" className={styles.textLink}>Protection Nuisibles : présence Google et acquisition</Link></p></div></section><ResourceReadings services={["google-ads","local-services"]} heading="Préparer votre acquisition payante" />
    <section className={styles.final} aria-labelledby="final-title"><Reveal className="container"><p className={styles.eyebrow}>PARTONS DE VOTRE OFFRE</p><h2 id="final-title">Une acquisition<br /><em>à cadrer ensemble.</em></h2><p>Votre offre, votre zone, vos campagnes actuelles et votre budget envisagé : parlons de ce qui doit être préparé et piloté.</p><Link href="/contact?service=ads" className="button button-primary">Parler de votre projet <span aria-hidden="true">↗</span></Link></Reveal></section>
  </div>;
}
