import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import styles from "../case-study.module.css";
const title="Nuisibles Toulon : site web & Google Ads local | CODE-V";
const description="Découvrez comment CODE-V a créé le site nuisibles-toulon.fr et accompagné son acquisition locale avec Google Ads.";
export const metadata: Metadata={title,description,alternates:{canonical:"https://www.code-v.fr/realisations/nuisibles-toulon"},robots:{index:true,follow:true},openGraph:{title,description,url:"https://www.code-v.fr/realisations/nuisibles-toulon",type:"website",locale:"fr_FR"}};
export default function Page(){return <div className={`${styles.page} ${styles.toulon}`}>
<header className={styles.hero}><div className="container"><Breadcrumb currentPath="/realisations/nuisibles-toulon" items={[{label:"Accueil",href:"/"},{label:"Réalisations",href:"/realisations"},{label:"Nuisibles Toulon"}]} /><div className={styles.split}><div><p className={styles.eyebrow}>TOULON ET ENVIRONS · SITE & GOOGLE ADS</p><h1>Créer le site.<br /><em>Capter la demande locale.</em></h1></div><div><p className={styles.lead}>Pour Nuisibles Toulon, CODE-V a créé le site web et mis en place une campagne Google Ads pour l’acquisition locale.</p><ul className={styles.flow}>{["Une recherche locale","Une annonce","Le site","La prise de contact"].map(item=><li key={item}>{item}</li>)}</ul></div></div></div></header>
<section className={styles.section}><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>LE BESOIN LOCAL</p><h2>Rencontrer une demande<br />dans la zone d’intervention.</h2></div><div><p>L’acquisition concerne Toulon et ses environs. Le dispositif associe un site de présentation de l’activité à une campagne Google Ads : un point d’arrivée et un levier pour y conduire les personnes recherchant un service local.</p><p>L’intervention validée de CODE-V porte sur ces deux éléments : création du site et mise en place de la campagne.</p></div></Reveal></section>
<section className={styles.section}><div className="container"><p className={styles.eyebrow}>LE SITE NUISIBLES-TOULON.FR</p><h2>Une destination pour le parcours d’acquisition.</h2><figure className={styles.media}><Image unoptimized src="/projects/nuisibles-toulon/home.webp" alt="Capture réelle de la page d’accueil du site Nuisibles Toulon créé par CODE-V." width={1440} height={1000} sizes="(max-width: 1200px) 100vw, 1180px" /><figcaption>Page d’accueil du site public, capture du 4 octobre 2026.</figcaption></figure><Link href="/creation-site" className={styles.link}>Découvrir la création de site</Link></div></section>
<section className={styles.dark}><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>GOOGLE ADS</p><h2>La recherche locale<br /><em>comme point d’entrée.</em></h2></div><div><p>CODE-V a mis en place une campagne Google Ads pour le client. Les annonces sponsorisées constituent le levier retenu pour l’acquisition locale.</p><p>Ce projet illustre la complémentarité entre publicité et site : l’annonce crée un point d’entrée, le site permet de découvrir l’activité et de poursuivre le parcours vers un contact.</p><Link href="/publicite" className={styles.link}>Découvrir Google Ads</Link></div></Reveal></section>
<section className={styles.section}><div className="container"><p className={styles.eyebrow}>UNE VISIBILITÉ OBSERVÉE</p><h2>Une annonce dans la recherche locale.</h2><p>Sur la recherche observée à Toulon, nuisibles-toulon.fr apparaît en première position sponsorisée au moment de la capture.</p><figure className={`${styles.media} ${styles.evidence}`}><a href="/projects/nuisibles-toulon/google-ads-first-position.webp" className={styles.link} aria-label="Afficher la capture Google originale en grand"><Image unoptimized src="/projects/nuisibles-toulon/google-ads-first-position.webp" alt="Sur la recherche observée à Toulon, nuisibles-toulon.fr apparaît en première position sponsorisée au moment de la capture." width={750} height={1334} sizes="(max-width: 800px) calc(100vw - 36px), 650px" /></a><figcaption>Sur la recherche observée à Toulon, nuisibles-toulon.fr apparaît en première position sponsorisée au moment de la capture.<br />La position sponsorisée peut varier selon la requête, l’enchère, la concurrence et le contexte de recherche.</figcaption></figure></div></section>
<section className={styles.final}><div className="container"><h2>Relier votre site<br /><em>à votre acquisition locale.</em></h2><p>Faisons le point sur votre offre, votre zone et le rôle d’une campagne Google Ads.</p><div className={styles.actions}><Link href="/contact?service=ads" className="button button-primary">Étudier une campagne</Link><Link href="/publicite" className={styles.link}>Découvrir la publicité en ligne</Link><Link href="/realisations" className={styles.link}>Voir les réalisations</Link></div></div></section></div>}

