import ReviewsSection from "@/components/ReviewsSection";
import { getReviewsByIds } from "@/data/reviews";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import NarrativeFilm from "@/components/media/NarrativeFilm";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import { getPublishedProjects } from "@/data/projects";
import { getResourcesByService } from "@/data/resources";
import styles from "./page.module.css";

const canonical = "https://www.code-v.fr/referencement";
const title = "Référencement naturel : accompagnement SEO | CODE-V";
const description = "Structure, technique, contenus et maillage : CODE-V accompagne le référencement naturel de votre site, du diagnostic aux optimisations et au suivi, sans position garantie.";
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR" } };
const structuredData = { "@context": "https://schema.org", "@type": "Service", name: "Accompagnement en référencement naturel", serviceType: "Référencement naturel", description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
const questions = [
  ["Combien de temps prend le référencement naturel ?", "Les effets dépendent de l’état du site, de la concurrence, des actions réalisées et des décisions des moteurs. Certaines corrections sont rapides à mettre en œuvre, mais la visibilité se suit dans le temps. Nous ne garantissons ni délai de résultat ni position."],
  ["Quelle différence entre SEO et Google Ads ?", "Le SEO travaille la présence dans les résultats organiques. Google Ads permet de diffuser des annonces payantes avec un budget média et des conditions de campagne propres. Les deux approches peuvent être complémentaires ; le référencement naturel ne consiste pas à acheter une position publicitaire."],
  ["Faut-il refaire mon site pour améliorer son SEO ?", "Pas systématiquement. Le diagnostic permet de distinguer les corrections possibles sur le site actuel d’une limite structurelle qui justifierait une refonte. Une refonte, si nécessaire, fait l’objet d’un périmètre distinct, avec attention aux URL et à la migration."],
  ["Pouvez-vous travailler sur un site existant ?", "Oui, après vérification de la technologie, des accès, des contenus et des contraintes. Les actions possibles et les responsabilités sont définies avant intervention. Nous n’annonçons pas une prise en charge universelle sans examiner ces éléments."],
  ["Comment mesure-t-on les progrès ?", "Avec les données réellement disponibles : exploration et indexation, requêtes, impressions et clics de Search Console, puis actions utiles sur le site si leur mesure est configurée. Les périodes et changements sont contextualisés. Un clic n’est pas un prospect et une position isolée ne résume pas la performance."],
  ["Quelle différence entre SEO général et SEO local ?", "Le SEO général travaille la structure et la pertinence du site pour les recherches liées à votre activité. Le SEO local ajoute la dimension géographique, Google Business Profile et Maps. Cette page présente l’accompagnement organique du site ; une demande locale nécessite un cadrage spécifique."],
  ["Que comprend l’accompagnement ?", "Selon le devis : diagnostic, priorités techniques et éditoriales, actions convenues et suivi. Le volume de rédaction, une refonte complète, les campagnes publicitaires et le suivi avancé des conversions ne sont pas inclus automatiquement. Aucun trafic ni classement n’est garanti."],
];

export default function ReferencementPage() {
  const proof = getPublishedProjects().find(project => project.id === "narbonne-toiture");
  const resources = getResourcesByService("seo");
  return <div className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <section className={styles.hero} aria-labelledby="seo-title"><div className="container"><Breadcrumb {...getPageBreadcrumb("/referencement")} />
      <div className={styles.heroGrid}><div><p className={styles.eyebrow}>RÉFÉRENCEMENT NATUREL / CODE-V</p><h1 id="seo-title">Le SEO.<br /><em>Un système à construire.</em></h1><p className={styles.lead}>Être trouvé commence par un site que l’on peut explorer, comprendre et utiliser. Nous relions sa structure, ses contenus et ses parcours pour travailler une visibilité pertinente, sans promettre une place sur Google.</p><Link href="/contact?service=seo" className="button button-primary">Parler de votre visibilité <span aria-hidden="true">↗</span></Link><p className={styles.note}>Diagnostic, actions et suivi définis selon votre site et votre besoin.</p></div>
      <Reveal className={styles.architecture}><figure><div className={styles.root}><span>UNE STRUCTURE DE SITE</span><strong>Un sujet central.</strong></div><div className={styles.branches}><div><span>Comprendre l’offre</span><Link href="/solutions">Solutions <i aria-hidden="true">↗</i></Link></div><div><span>Observer le travail</span><Link href="/realisations">Réalisations <i aria-hidden="true">↗</i></Link></div><div><span>Approfondir</span><Link href="/ressources">Ressources <i aria-hidden="true">↗</i></Link></div></div><div className={styles.connection}><span>Des pages distinctes.</span><strong>Des liens utiles.</strong></div><figcaption>Une architecture claire relie les solutions, les réalisations et les ressources utiles.</figcaption></figure></Reveal></div>
      <nav className={styles.chapterNav} aria-label="Parcours référencement"><a href="#diagnostic">Diagnostiquer</a><a href="#fondations">Structurer</a><a href="#suivi">Suivre & optimiser</a><a href="#questions">Vos questions</a></nav>
    </div></section>

    <section className={styles.intro} aria-labelledby="intro-title"><Reveal className={`container ${styles.introGrid}`}><p className={styles.eyebrow}>PAS DE MAGIE. UNE STRATÉGIE.</p><div><h2 id="intro-title">Une page existe.<br /><span>Encore faut-il pouvoir la trouver.</span></h2><p>Le référencement d’un site internet ne se limite pas à ajouter des mots clés. Les moteurs doivent pouvoir accéder aux pages, comprendre ce qu’elles apportent et les proposer pour des recherches pertinentes. L’exploration, l’indexation et l’affichage dans les résultats sont des étapes distinctes, sans garantie automatique.</p><div className={styles.searchFlow} aria-label="Exploration, indexation, recherche"><span>Exploration</span><i aria-hidden="true">→</i><span>Indexation</span><i aria-hidden="true">→</i><span>Recherche</span></div><p className={styles.note}>Un parcours simplifié : une page explorée n’est pas nécessairement indexée ou affichée.</p></div></Reveal>
      <div className={styles.filmStage}><NarrativeFilm src="/videos/seo.mp4" srcSmall="/videos/seo-720.mp4" poster="/videos/seo-poster.webp" width={1920} height={1080} loop controlsAt="top" title="Comment un site devient visible pour les bonnes recherches" description="Un site presque invisible flotte dans un grand espace de recherche : être en ligne ne suffit pas. Ses pages se rangent en arborescence, reçoivent titres et contenus, puis se relient par des liens internes. Une exploration parcourt les pages ; celles qui sont retenues rejoignent un index, une page d’archive n’y entre pas. Une requête, création site professionnel, est reliée aux pages pertinentes et le site remonte parmi des résultats abstraits, sans position annoncée. Un clic mène directement à la page Création de site professionnel, qui est lue jusqu’au bouton de demande de devis. Le film se termine sur le logo CODE-V : le SEO, un système à construire. Une ambiance électronique discrète accompagne le film quand on active le son." /></div>
    </section>

    <section id="diagnostic" className={styles.diagnostic} aria-labelledby="diagnostic-title"><div className={`container ${styles.diagnosticGrid}`}><Reveal><p className={styles.eyebrow}>PARTIR DE L’EXISTANT</p><h2 id="diagnostic-title">Ce qui bloque.<br /><span>Ce qui manque.<br />Ce qui mérite une priorité.</span></h2><p>Pages difficiles à découvrir, contenus qui se recouvrent, navigation sans liens utiles ou parcours qui n’aboutissent pas : les causes ne se traitent pas toutes de la même façon.</p><Link href="/contact?service=seo" className={styles.textLink}>Faire le point sur votre référencement <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.auditSheet}><p className={styles.eyebrow}>CE QUE LE DIAGNOSTIC CHERCHE À ÉCLAIRER</p><dl><div><dt>Le site et ses contraintes</dt><dd>Technologie, accès, pages utiles, obstacles à l’exploration et règles d’indexation.</dd></div><div><dt>Les recherches à servir</dt><dd>Votre offre, les intentions des visiteurs et les réponses réellement apportées par les contenus.</dd></div><div><dt>Les données disponibles</dt><dd>Les données de Search Console et des outils configurés éclairent les prochaines actions.</dd></div><div><dt>L’ordre des actions</dt><dd>Corrections, contenus et maillage à prioriser selon leur rôle, leurs dépendances et les moyens disponibles.</dd></div></dl></Reveal></div></section>

    <section id="fondations" className={styles.foundations} aria-labelledby="foundations-title"><div className="container"><Reveal className={styles.sectionHeading}><p className={styles.eyebrow}>LES FONDATIONS DU RÉFÉRENCEMENT</p><h2 id="foundations-title">La technique ouvre le passage.<br /><em>Le contenu lui donne un sens.</em></h2></Reveal>
      <div className={styles.editorialRow}><Reveal><span className={styles.marker}>ACCÉDER</span><h3>Une base technique accessible.</h3></Reveal><Reveal><p>Nous examinons les pages accessibles aux moteurs, les codes de réponse, les redirections et les indications d’indexation. Les canonical et les éventuels doublons se traitent dans le contexte du site, pas par une règle appliquée à toutes les URL.</p><p>La performance et l’usage mobile sont vérifiés pour limiter les frictions. Un score technique ne garantit ni classement ni conversion.</p></Reveal></div>
      <div className={styles.editorialRow}><Reveal><span className={styles.marker}>COMPRENDRE</span><h3>Une intention.<br />Une réponse claire.</h3></Reveal><Reveal><p>La stratégie sémantique précise les questions et besoins que chaque page doit servir. Titres, contenus et structure soutiennent cette réponse, sans répéter artificiellement un mot clé.</p><p>Une page commerciale explique une prestation ; un guide approfondit une question. Si deux pages remplissent le même rôle, il faut clarifier leurs intentions avant de produire davantage de texte.</p></Reveal></div>
      <div className={styles.editorialRow}><Reveal><span className={styles.marker}>RELIER</span><h3>Le maillage fait circuler<br />la compréhension.</h3></Reveal><Reveal><p>Des liens descriptifs relient les pages pertinentes : offre, ressource utile, réalisation puis contact. Ils aident le lecteur à poursuivre et les moteurs à découvrir les contenus.</p><p>Nous évitons les liens ajoutés uniquement pour multiplier les ancres. L’architecture et les contenus doivent rester compréhensibles même sans explication SEO.</p><Link href="/ressources" className={styles.textLink}>Explorer les repères CODE-V <span aria-hidden="true">↗</span></Link></Reveal></div>
    </div></section>

    <section id="suivi" className={styles.tracking} aria-labelledby="tracking-title"><div className={`container ${styles.trackingGrid}`}><Reveal><p className={styles.eyebrow}>OBSERVER, PUIS AJUSTER</p><h2 id="tracking-title">Les actions se suivent.<br /><span>Les conclusions se vérifient.</span></h2><p>Les changements sont documentés, les données comparées sur des périodes pertinentes et les prochaines actions réévaluées. L’optimisation continue ne consiste pas à publier sans regarder ce qui se passe.</p><Link href="/contact?service=seo" className={styles.textLink}>Construire une stratégie SEO <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.observation}><h3>De la visibilité à l’action utile.</h3><p>Impressions, clics et requêtes éclairent la présence organique. Les prises de contact apportent un autre niveau de lecture, lorsque leur mesure est effectivement configurée.</p><p>Un visiteur doit aussi comprendre l’offre, trouver une preuve et pouvoir agir. Le SEO et la conversion se répondent, sans confondre trafic, demande et client.</p><p className={styles.note}>Périmètre des optimisations, volume de rédaction et fréquence du suivi précisés au devis. Ni acquisition payante ni refonte complète incluses automatiquement.</p></Reveal></div></section>

    <section className={styles.proof} aria-labelledby="proof-title"><div className={`container ${styles.proofGrid}`}><Reveal><p className={styles.eyebrow}>LES FONDATIONS EN PRATIQUE</p><h2 id="proof-title">Des projets concrets.<br /><span>Une approche mesurable.</span></h2><p>Nous concevons des sites structurés pour être compris, parcourus et optimisés dans le temps. Architecture, contenus, performance et maillage sont travaillés comme les fondations d’une stratégie SEO durable.</p><Link href="/realisations" className={styles.textLink}>Voir nos réalisations <span aria-hidden="true">↗</span></Link></Reveal>{proof?.coverImage && <Reveal className={styles.proofMedia}><figure><Image src={proof.coverImage.src} alt={proof.coverImage.alt} width={proof.coverImage.width} height={proof.coverImage.height} sizes="(max-width: 900px) calc(100vw - 36px), 600px" /><figcaption>{proof.name} — réalisation web CODE-V.</figcaption></figure></Reveal>}</div></section>

    <ReviewsSection reviews={getReviewsByIds(["stephane-sivan"])} heading="Le regard de nos clients." variant="inline" maxItems={1} compact />    <section className={styles.boundaries} aria-labelledby="boundaries-title"><div className="container"><Reveal className={styles.boundaryGrid}><div><p className={styles.eyebrow}>LE BON PÉRIMÈTRE</p><h2 id="boundaries-title">Améliorer le site.<br /><span>Choisir le bon accompagnement.</span></h2></div><div><h3>Une refonte n’est pas systématique.</h3><p>Nous distinguons les optimisations du site actuel d’un besoin de reconstruction. Si la structure ne peut plus répondre à vos usages, un projet de site sera cadré séparément.</p><Link href="/creation-site" className={styles.textLink}>Comprendre la création et la refonte de site <span aria-hidden="true">↗</span></Link><h3>Une demande locale a ses particularités.</h3><p>Google Business Profile, Maps et les recherches géographiques relèvent d’un accompagnement local spécifique. Ici, nous traitons le référencement organique du site ; le volet local se précise selon votre activité et votre zone.</p><Link href="/referencement-local" className={styles.textLink}>Découvrir le référencement local <span aria-hidden="true">↗</span></Link><Link href="/solutions" className={styles.textLink}>Explorer les autres leviers CODE-V <span aria-hidden="true">↗</span></Link></div></Reveal></div></section>

    <section id="questions" className={styles.faq} aria-labelledby="faq-title"><div className="container"><Reveal className={styles.faqHeading}><p className={styles.eyebrow}>AVANT DE DÉFINIR LA SUITE</p><h2 id="faq-title">Vos questions sur<br /><span>l’accompagnement SEO.</span></h2></Reveal><div className={styles.faqList}>{questions.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    {resources.length > 0 && <section className={styles.reading}><div className="container"><h2>Pour approfondir</h2>{resources.map(resource => <Link key={resource.id} href={`/ressources/${resource.slug}`} className={styles.textLink}>{resource.title}<span aria-hidden="true">↗</span></Link>)}</div></section>}
    <section className={styles.final} aria-labelledby="final-title"><Reveal className="container"><p className={styles.eyebrow}>PARTONS DE VOTRE SITE</p><h2 id="final-title">Une visibilité à travailler.<br /><em>Une stratégie à cadrer.</em></h2><p>Parlez-nous de votre activité, de votre site et des recherches sur lesquelles vous souhaitez être trouvé. Nous préciserons ce qui peut être examiné et accompagné.</p><Link href="/contact?service=seo" className="button button-primary">Parler de votre projet <span aria-hidden="true">↗</span></Link></Reveal></section>
  </div>;
}
