import ReviewsSection from "@/components/ReviewsSection";
import { getReviewsByIds } from "@/data/reviews";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import { getPublishedProjects } from "@/data/projects";
import styles from "./page.module.css";

const canonical = "https://www.code-v.fr/maintenance-site";
const title = "Maintenance de site internet & support | CODE-V";
const description = "Après la mise en ligne, CODE-V accompagne l’entretien de votre site : vérifications, mises à jour, corrections et petites évolutions, dans un périmètre convenu.";
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR" } };
const service = { "@context": "https://schema.org", "@type": "Service", name: "Maintenance de sites", serviceType: "Maintenance de site internet", description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
const questions = [
  ["Pourquoi maintenir un site internet ?", "Le site continue de vivre après sa livraison : logiciels, contenus, services externes et usages évoluent. L’entretien permet de vérifier les fonctions utiles, de traiter les corrections et de préparer les changements plutôt que de laisser les petits problèmes s’accumuler."],
  ["Que comprend une maintenance ?", "Le périmètre est convenu selon le site : vérifications, mises à jour, sauvegardes, corrections, assistance ou petites modifications. La fréquence, les horaires, les responsabilités et les conditions d’intervention sont précisés au devis. Une refonte ou une fonctionnalité importante constitue un projet distinct."],
  ["Faut-il maintenir un site Next.js ?", "Oui, le besoin d’entretien ne dépend pas seulement du CMS. Un site Next.js peut utiliser des dépendances, des formulaires et des services externes à suivre. Les mises à jour et vérifications se préparent selon son architecture et son mode de déploiement."],
  ["Maintenance et hébergement, est-ce la même chose ?", "Non. L’hébergement fournit l’environnement dans lequel le site est servi. La maintenance porte sur son entretien et ses fonctions. Sauvegardes, supervision et interventions doivent être réparties clairement entre les prestataires ; l’hébergement est distinct sauf devis commun."],
  ["Pouvez-vous reprendre un site créé par quelqu’un d’autre ?", "La reprise se décide après examen de la technologie, du code ou du CMS, des accès, des licences et des sauvegardes. Cet état des lieux permet de préciser ce qui peut être pris en charge et les éventuelles actions préalables."],
  ["Peut-on faire évoluer un site existant ?", "Oui, selon ses possibilités techniques. Une correction de contenu ou un ajustement simple peut entrer dans l’accompagnement convenu. Un nouveau parcours, une intégration importante ou une reconstruction demande un cadrage séparé."],
  ["Faut-il une maintenance si le site fonctionne aujourd’hui ?", "Un site fonctionnel mérite un suivi proportionné à ses usages : un site de présentation n’a pas les mêmes besoins qu’une boutique ou un outil connecté. Nous définissons les contrôles utiles et le rythme adapté, sans multiplier les interventions inutiles."],
];

export default function MaintenancePage() {
  const example = getPublishedProjects().find(project => project.id === "chateau-de-projan");
  return <div className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(service).replace(/</g, "\\u003c") }} />
    <section className={styles.hero} aria-labelledby="care-title"><div className="container"><Breadcrumb {...getPageBreadcrumb("/maintenance-site")} /><div className={styles.heroGrid}>
      <div><p className={styles.eyebrow}>MAINTENANCE DE SITE / CODE-V</p><h1 id="care-title">En ligne.<br /><em>Et bien accompagné.</em></h1><p className={styles.lead}>Après la mise en ligne, votre site reste un point de contact pour vos clients. CODE-V organise son entretien, les vérifications utiles et les petites évolutions pour vous permettre d’avancer avec un interlocuteur identifié.</p><Link href="/contact?service=website-care" className="button button-primary">Faire le point sur votre site <span aria-hidden="true">↗</span></Link></div>
      <Reveal className={styles.cycle}><figure><p>LA CONTINUITÉ DU SITE</p><div className={styles.cycleCenter}>Votre site.<br /><strong>Dans la durée.</strong></div><ol><li>Observer</li><li>Préparer</li><li>Intervenir</li><li>Vérifier</li></ol><figcaption>Des contrôles et des interventions reliés, selon le périmètre convenu.</figcaption></figure></Reveal>
    </div><nav className={styles.chapterNav} aria-label="Parcours maintenance"><a href="#supervision">Les vérifications</a><a href="#entretien">L’entretien</a><a href="#evolutions">Les évolutions</a><a href="#questions">Vos questions</a></nav></div></section>

    <section className={styles.intro} aria-labelledby="intro-title"><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>APRÈS LA MISE EN LIGNE</p><h2 id="intro-title">Le site est livré.<br /><span>La relation continue.</span></h2></div><div><p>Un formulaire qui ne transmet plus, un contenu devenu obsolète, un affichage modifié après une mise à jour : ces sujets font partie de la vie d’un site. Leur prise en charge mérite un cadre simple et un responsable.</p><p>La maintenance vise la continuité des usages, pas une accumulation de tâches techniques. Nous partons de ce qui compte pour votre activité et précisons les points à suivre, les accès et les modalités d’assistance.</p></div></Reveal></section>

    <section id="supervision" className={styles.supervision} aria-labelledby="supervision-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>SUIVRE CE QUI EST UTILE</p><h2 id="supervision-title">Le contact.<br /><span>Le parcours. L’usage.</span></h2><p>Les vérifications sont définies selon votre site et ses fonctions critiques. Nous distinguons les contrôles programmés, les alertes disponibles et les demandes que votre équipe nous transmet.</p><Link href="/contact?service=website-care" className={styles.textLink}>Confier la maintenance <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.checks}><div><h3>Les fonctions qui font le lien.</h3><p>Formulaires, liens de contact et connexions utiles : vérifier le parcours jusqu’à son aboutissement permet d’identifier un dysfonctionnement au bon endroit.</p></div><div><h3>La qualité d’usage.</h3><p>Pages accessibles, affichage mobile et lenteurs observées : les contrôles de performance et d’interface éclairent les corrections à prioriser.</p></div><div><h3>Un suivi compréhensible.</h3><p>Les constats et interventions sont partagés dans le cadre convenu. Vous savez ce qui a été traité et quelles actions demandent une décision.</p></div></Reveal></div></section>

    <section id="entretien" className={styles.entretien} aria-labelledby="entretien-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>ENTRETENIR SANS PRÉCIPITER</p><h2 id="entretien-title">Préparer le changement.<br /><em>Vérifier ce qui suit.</em></h2></Reveal><div className={styles.editorialRow}><Reveal><h3>Mises à jour<br />et compatibilité.</h3></Reveal><Reveal><p>Selon la technologie, l’entretien porte sur le CMS, ses extensions ou les dépendances de l’application. WordPress et Next.js ne se maintiennent pas de la même façon : nous examinons les versions, les fonctions et les conditions de déploiement avant intervention.</p><p>Les changements sont préparés et les parcours concernés vérifiés. Un environnement de test peut être prévu lorsque le site et le périmètre le permettent.</p></Reveal></div><div className={styles.editorialRow}><Reveal><h3>Sauvegardes<br />et sécurité.</h3></Reveal><Reveal><p>Les éléments à sauvegarder dépendent du site : fichiers, code, contenus et données. Leur conservation et les modalités de restauration sont cadrées avec l’hébergement et les autres intervenants.</p><p>Le suivi des mises à jour et des accès contribue à la prévention. Les vérifications de restauration, leur fréquence et les actions de sécurité sont définies dans l’accompagnement.</p></Reveal></div><div className={styles.editorialRow}><Reveal><h3>Corrections<br />et incidents.</h3></Reveal><Reveal><p>Nous qualifions le problème, identifions les fonctions concernées et convenons de l’action appropriée. Une correction doit être suivie d’une vérification du parcours, pas seulement d’un changement de code.</p><p>Les moyens de signalement, horaires et conditions d’intervention sont précisés avant la prise en charge. Les incidents liés à un service tiers sont traités selon les accès et responsabilités de chacun.</p></Reveal></div></div></section>

    <section id="evolutions" className={styles.evolutions} aria-labelledby="evolutions-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>GARDER LE SITE EN PHASE AVEC L’ACTIVITÉ</p><h2 id="evolutions-title">Corriger aujourd’hui.<br /><span>Faire évoluer demain.</span></h2><p>Une information à actualiser, un lien à corriger ou un petit ajustement d’interface : les modifications simples peuvent entrer dans un volume convenu. L’assistance vous aide à préciser le besoin avant d’agir.</p><Link href="/contact?service=website-care" className={styles.textLink}>Parler de vos besoins <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.scope}><h3>Maintenance ou refonte ?</h3><p>La maintenance entretient l’existant. Si les objectifs, les parcours ou l’architecture doivent changer en profondeur, un projet de refonte sera cadré séparément.</p><p>Les nouvelles fonctions, intégrations importantes et volumes de contenu dépassant le cadre convenu font l’objet d’une estimation dédiée.</p><Link href="/creation-site" className={styles.textLink}>Comprendre la création et la refonte de site <span aria-hidden="true">↗</span></Link><Link href="/solutions/web-applications" className={styles.textLink}>Explorer le Web & les applications <span aria-hidden="true">↗</span></Link></Reveal></div></section>

    <section className={styles.hosting} aria-labelledby="hosting-title"><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>DES RESPONSABILITÉS LISIBLES</p><h2 id="hosting-title">L’hébergement sert le site.<br /><span>La maintenance l’entretient.</span></h2></div><div><p>Hébergement, nom de domaine, messagerie et maintenance ont des rôles distincts. Nous précisons qui gère les accès, les sauvegardes et les interventions, avec votre prestataire actuel ou dans un devis commun.</p><p>Une reprise commence par un état des lieux : technologie, accès techniques, licences, sauvegardes et fonctions essentielles. Le rythme du suivi et les demandes d’évolution se définissent ensuite selon votre activité.</p><p>Vous gardez une lecture claire du travail réalisé et des prochaines décisions, dans un accompagnement continu ou des interventions convenues.</p></div></Reveal></section>

    {example?.coverImage && <section className={styles.proof} aria-labelledby="proof-title"><div className={`container ${styles.proofGrid}`}><Reveal><p className={styles.eyebrow}>LE WEB, DANS SES USAGES CONCRETS</p><h2 id="proof-title">Des sites pensés<br /><span>pour votre activité.</span></h2><p>Les réalisations CODE-V montrent des interfaces, des contenus et des parcours de contact adaptés à différents métiers.</p><Link href="/realisations" className={styles.textLink}>Voir nos réalisations <span aria-hidden="true">↗</span></Link></Reveal><Reveal><figure><Image src={example.coverImage.src} alt={example.coverImage.alt} width={example.coverImage.width} height={example.coverImage.height} sizes="(max-width: 900px) calc(100vw - 36px), 600px" /><figcaption>{example.name} — réalisation web CODE-V.</figcaption></figure></Reveal></div></section>}
    <ReviewsSection reviews={getReviewsByIds(["andre-picard", "pierre-louis"])} heading="Le suivi compte aussi." variant="compact" maxItems={2} compact />    <section id="questions" className={styles.faq} aria-labelledby="faq-title"><div className="container"><Reveal><p className={styles.eyebrow}>DÉFINIR LA SUITE</p><h2 id="faq-title">Vos questions<br /><span>sur la maintenance.</span></h2></Reveal><div className={styles.faqList}>{questions.map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><Link href="/ressources" className={styles.textLink}>Explorer les ressources CODE-V <span aria-hidden="true">↗</span></Link></div></section>
    <section className={styles.final} aria-labelledby="final-title"><Reveal className="container"><p className={styles.eyebrow}>UN INTERLOCUTEUR POUR LA SUITE</p><h2 id="final-title">Votre site évolue.<br /><em>Son accompagnement aussi.</em></h2><p>Partagez l’adresse de votre site, sa technologie si vous la connaissez et les sujets à suivre. Nous préciserons la reprise et le périmètre d’entretien adapté.</p><Link href="/contact?service=website-care" className="button button-primary">Parler de votre site <span aria-hidden="true">↗</span></Link></Reveal></section>
  </div>;
}
