import ResourceReadings from "@/components/resources/ResourceReadings";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import Reveal from "@/components/motion/Reveal";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import { getPublishedProjects } from "@/data/projects";
import styles from "./page.module.css";

const canonical = "https://www.code-v.fr/referencement-local";
const title = "Référencement local & Google Business Profile | CODE-V";
const description = "CODE-V accompagne votre visibilité locale : fiche Google Business Profile, cohérence des informations, site et suivi. Parlons de votre activité et de votre zone.";
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR" } };
const service = { "@context": "https://schema.org", "@type": "Service", name: "SEO local & Google Business Profile", serviceType: "Référencement local", description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
const faq = [
  ["Qu’est-ce que le référencement local ?", "C’est le travail de votre présence sur les recherches liées à un lieu ou à une proximité. Il associe les informations de votre établissement, Google Business Profile, votre site et les éléments qui aident un client à choisir puis à vous contacter."],
  ["Quelle différence entre SEO général et SEO local ?", "Le SEO général travaille la structure, la technique et les contenus du site. Le SEO local ajoute le contexte géographique, la fiche d’établissement et Maps. Les deux démarches se complètent, avec des priorités adaptées à votre activité."],
  ["Faut-il une fiche Google Business Profile ?", "Elle est utile pour les activités éligibles qui accueillent des clients ou se déplacent chez eux. Une entreprise uniquement en ligne n’est généralement pas éligible. Nous vérifions votre situation avant d’étudier une création ou une optimisation de fiche."],
  ["Les avis influencent-ils la visibilité locale ?", "Google indique que le nombre d’avis et les notes participent au classement local, avec d’autres facteurs. Les avis aident aussi les clients à se faire une idée de votre activité. Nous travaillons une démarche de retour authentique et des réponses utiles, sans achat d’avis ni contrepartie."],
  ["Faut-il créer une page pour chaque ville ?", "Non. Une page locale se justifie par une zone réellement servie et un contenu utile qui lui est propre : intervention, établissement ou informations pratiques. Dupliquer un texte en changeant le nom de la ville n’aide pas le visiteur à comprendre votre offre."],
  ["Combien de temps faut-il pour améliorer sa visibilité locale ?", "Le délai dépend de la situation initiale, des accès, des validations Google, de la concurrence et des actions réalisées. Nous définissons les priorités et les points de suivi ; aucune position ni date de résultat ne peut être garantie."],
  ["Pouvez-vous travailler sur une fiche existante ?", "Oui, après vérification de sa propriété, des accès et de son état. Nous commençons par les informations de l’activité et les incohérences à corriger. Le périmètre est convenu avant intervention, y compris pour plusieurs établissements."],
];

export default function LocalSeoPage() {
  const examples = getPublishedProjects().filter(project => ["peinture-occitane", "express-nuisibles", "narbonne-toiture"].includes(project.id) && project.coverImage !== undefined);
  return <div className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(service).replace(/</g, "\\u003c") }} />
    <section className={styles.hero} aria-labelledby="local-title"><div className="container"><Breadcrumb {...getPageBreadcrumb("/referencement-local")} /><div className={styles.heroGrid}>
      <div><p className={styles.eyebrow}>SEO LOCAL / CODE-V</p><h1 id="local-title">Votre activité.<br /><em>Au bon endroit.</em></h1><p className={styles.lead}>Vos clients cherchent un service près de chez eux. CODE-V relie votre fiche Google, votre site et votre zone d’intervention pour rendre votre présence locale claire et faciliter la prise de contact.</p><Link href="/contact?service=seo" className="button button-primary">Parler de votre visibilité locale <span aria-hidden="true">↗</span></Link></div>
      <Reveal className={styles.localDiagram}><figure><div className={styles.map} aria-hidden="true"><svg viewBox="0 0 500 360" fill="none"><path d="M-20 80L190 120L340 25M80 380L190 120L520 200M-20 265L210 210L350 380M290 -20L210 210L520 70" stroke="#33465e" strokeWidth="16" /><path d="M-20 80L190 120L340 25M80 380L190 120L520 200M-20 265L210 210L350 380M290 -20L210 210L520 70" stroke="#58748d" strokeWidth="1" /><ellipse cx="255" cy="178" rx="130" ry="110" fill="#4f8cff" fillOpacity=".08" stroke="#4f8cff" strokeDasharray="5 8" /><circle cx="255" cy="178" r="28" fill="#50e3c2" /><path d="M245 177l7 7 13-14" stroke="#07111f" strokeWidth="3" /></svg><span className={styles.mapLabel}>Votre présence locale</span></div><div className={styles.connections}><span>Fiche Google</span><i aria-hidden="true">↔</i><span>Votre site</span><i aria-hidden="true">↔</i><span>Votre zone</span></div><figcaption>Une présence cohérente, de la recherche à la prise de contact.</figcaption></figure></Reveal>
    </div><nav className={styles.chapterNav} aria-label="Parcours SEO local"><a href="#fiche">Votre fiche Google</a><a href="#site">Votre site & votre zone</a><a href="#suivi">Le suivi</a><a href="#questions">Vos questions</a></nav></div></section>

    <section className={styles.context} aria-labelledby="context-title"><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>LE CLIENT CHERCHE UNE RÉPONSE PROCHE</p><h2 id="context-title">Être présent.<br /><span>Être identifiable.</span></h2></div><div><p>Un horaire qui diffère selon les supports, une activité mal décrite, une fiche sans lien vers le bon service : ces décalages compliquent le choix et le contact.</p><p>Artisans, commerces, restaurants, entreprises de services, professions de proximité ou établissements recevant du public : le point de départ est votre fonctionnement réel. Où accueillez-vous vos clients ? Où intervenez-vous ? Que cherchent-ils à obtenir ?</p><p>Les résultats locaux dépendent notamment de la pertinence, de la distance et de la notoriété. Une zone renseignée ne garantit pas une visibilité uniforme dans toutes les villes.</p></div></Reveal></section>

    <section id="fiche" className={styles.profile} aria-labelledby="profile-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>GOOGLE BUSINESS PROFILE</p><h2 id="profile-title">Une fiche qui décrit<br /><span>vraiment votre activité.</span></h2><p>Nous examinons l’existant, l’éligibilité et les accès. Puis nous cadrons les optimisations de votre fiche établissement selon votre lieu d’accueil ou votre zone de service.</p><Link href="/contact?service=seo" className={styles.textLink}>Faire le point sur votre fiche Google <span aria-hidden="true">↗</span></Link></Reveal><Reveal className={styles.profileDetail}><div><h3>Des informations qui concordent.</h3><p>Nom réel, coordonnées, horaires et zone desservie : la fiche et le site doivent raconter la même activité. Les catégories et services décrivent ce que vous faites, sans ajouter des mots clés au nom de l’établissement.</p></div><div><h3>Une présence qui se comprend.</h3><p>Description, services, photos de votre activité et informations pratiques permettent au visiteur de se repérer. Les contenus et publications répondent à de vraies nouveautés ; leur production régulière se définit selon vos moyens.</p></div><div><h3>Le bon cadre d’intervention.</h3><p>Une mise en place, une optimisation ponctuelle ou un suivi : les accès, les responsabilités, le nombre d’établissements et la cadence sont précisés au devis.</p></div></Reveal></div></section>

    <section id="site" className={styles.site} aria-labelledby="site-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>FICHE ↔ SITE ↔ RECHERCHE LOCALE</p><h2 id="site-title">La fiche ouvre le chemin.<br /><em>Le site explique la suite.</em></h2></Reveal><div className={styles.editorialRow}><Reveal><h3>Vos services.<br />Votre zone réelle.</h3></Reveal><Reveal><p>Votre site précise les prestations, les modalités d’intervention et les moyens de contact. Les informations géographiques apportent un contexte utile : établissement, zone desservie et détails pratiques.</p><p>Une page locale mérite un contenu propre à une situation réelle. Nous privilégions quelques pages utiles et reliées plutôt qu’une série de pages identiques pour chaque ville.</p></Reveal></div><div className={styles.editorialRow}><Reveal><h3>Un parcours lisible,<br />jusqu’à la demande.</h3></Reveal><Reveal><p>La fiche renvoie vers la page pertinente ; le maillage relie le service, les réalisations et le contact. Sur mobile, les coordonnées et les actions doivent rester faciles à trouver.</p><p>La structure technique et les contenus du site soutiennent ce parcours. Selon l’existant, des optimisations suffisent ou un projet de site mérite d’être cadré.</p><Link href="/creation-site" className={styles.textLink}>Découvrir la création et la refonte de site <span aria-hidden="true">↗</span></Link></Reveal></div><Link href="/contact?service=seo" className="button button-primary">Travailler votre présence locale <span aria-hidden="true">↗</span></Link></div></section>

    <section className={styles.reputation} aria-labelledby="reputation-title"><Reveal className={`container ${styles.split}`}><div><p className={styles.eyebrow}>UNE RELATION QUI SE VOIT</p><h2 id="reputation-title">Des retours authentiques.<br /><span>Des réponses attentives.</span></h2></div><div><h3>Avis et réputation.</h3><p>Inviter les clients à partager leur expérience et répondre avec précision fait partie de la relation commerciale. Nous vous aidons à cadrer une démarche simple, sans sélectionner uniquement les clients satisfaits ni offrir une contrepartie.</p><h3>Montrer le quotidien de l’activité.</h3><p>Des photos actuelles, les informations de service et des publications pertinentes donnent des repères avant la visite ou l’appel. Le rythme de production et de réponse doit rester compatible avec votre organisation.</p></div></Reveal></section>

    <section id="suivi" className={styles.tracking} aria-labelledby="tracking-title"><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>MESURER POUR CHOISIR LA SUITE</p><h2 id="tracking-title">Observer la présence.<br /><span>Comprendre les contacts.</span></h2><p>Nous suivons les données accessibles de la fiche et du site sur des périodes comparables, puis réévaluons les priorités. La visibilité sur Maps, les recherches géolocalisées et les demandes ne se lisent pas comme un classement unique.</p></Reveal><Reveal className={styles.trackingDetail}><h3>De la recherche à l’action.</h3><p>Vues, interactions avec la fiche, clics vers le site ou demandes d’itinéraire éclairent différents usages. La mesure des formulaires et des autres contacts sur le site se configure selon le périmètre convenu. Un clic sur un numéro n’est pas un appel abouti.</p><p>Le suivi aide à choisir entre correction d’informations, amélioration d’une page ou production de contenu utile.</p><Link href="/referencement" className={styles.textLink}>Comprendre le référencement naturel du site <span aria-hidden="true">↗</span></Link><Link href="/ressources" className={styles.textLink}>Explorer les ressources CODE-V <span aria-hidden="true">↗</span></Link></Reveal></div></section>

    {examples.length > 0 && <section className={styles.proof} aria-labelledby="proof-title"><div className="container"><Reveal className={styles.sectionHead}><p className={styles.eyebrow}>DES ACTIVITÉS, DES INTERFACES</p><h2 id="proof-title">Des sites pour<br /><span>des métiers de proximité.</span></h2><p>Quelques réalisations web CODE-V : des façons de présenter une activité et de faciliter le contact.</p></Reveal><div className={styles.examples}>{examples.map(project => <Reveal key={project.id}><figure><Image src={project.coverImage!.src} alt={project.coverImage!.alt} width={project.coverImage!.width} height={project.coverImage!.height} sizes="(max-width: 900px) calc(100vw - 36px), 600px" /><figcaption><h3>{project.name}</h3><span>Réalisation web CODE-V</span></figcaption></figure></Reveal>)}</div><Link href="/realisations" className={styles.textLink}>Voir nos réalisations <span aria-hidden="true">↗</span></Link></div></section>}

    <section id="questions" className={styles.faq} aria-labelledby="faq-title"><div className="container"><Reveal><p className={styles.eyebrow}>PRÉCISER VOTRE BESOIN</p><h2 id="faq-title">Vos questions<br /><span>sur le SEO local.</span></h2></Reveal><div className={styles.faqList}>{faq.map(([question,answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <ResourceReadings services={["local-seo"]} heading="Comprendre votre présence locale" />
    <section className={styles.final} aria-labelledby="final-title"><Reveal className="container"><p className={styles.eyebrow}>VOTRE ACTIVITÉ, VOTRE TERRAIN</p><h2 id="final-title">Une présence locale<br /><em>à construire ensemble.</em></h2><p>Parlons de votre établissement ou de votre zone d’intervention, de votre fiche Google et de votre site. Nous définirons les priorités et le périmètre adapté.</p><Link href="/contact?service=seo" className="button button-primary">Parler de votre projet <span aria-hidden="true">↗</span></Link></Reveal></section>
  </div>;
}
