import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import MotionVideo from "@/components/media/MotionVideo";
import Reveal from "@/components/motion/Reveal";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import { projects } from "@/data/projects";
import { getServiceById } from "@/data/services";
import styles from "./page.module.css";
const title = "Motion design & vidéos explicatives | CODE-V";
const description = "Donnez une forme claire à votre message : motion design, vidéos explicatives et formats de communication adaptés aux supports de votre entreprise.";
const canonical = "https://www.code-v.fr/motion-design";
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical, type: "website", locale: "fr_FR" } };
export default function MotionDesignPage() {
  const film = projects.find(project => project.id === "code-v-motion" && project.status === "published")?.video;
  const service = getServiceById("video-motion")!;
  const schema = { "@context": "https://schema.org", "@type": "Service", name: service.name, description, url: canonical, provider: { "@type": "Organization", name: "CODE-V", url: "https://www.code-v.fr" } };
  return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <section className={styles.hero}><div className="container"><Breadcrumb {...getPageBreadcrumb("/motion-design")} /><p className={styles.eyebrow}>MOTION DESIGN / VIDÉO</p><div className={styles.heading}><h1>Un message.<br /><em>Une mise en mouvement.</em></h1><div><p>Expliquer une offre, montrer un parcours ou donner du relief à une présentation. Nous construisons un format animé autour de ce que votre public doit comprendre.</p><Link href="/contact?service=video-motion" className={styles.link}>Étudier votre format vidéo ↗</Link></div></div></div></section>
    {film && <section className={styles.cinema} aria-label="Film motion CODE-V"><div className="container"><div className={styles.filmIntro}><p className={styles.eyebrow}>DÉMONSTRATION DE MARQUE CODE-V</p><p>Un film qui met en scène les connexions entre site, outils et parcours client.</p></div><MotionVideo src={film.src} poster={film.poster} title={film.title} mode="explainer" controls muted={false} transcript={film.description} transcriptLabel="Lire la description du film" /><Link href="/realisations#laboratoire" className={styles.link}>Découvrir le laboratoire CODE-V ↗</Link></div></section>}
    <section className={styles.story}><div className={`container ${styles.split}`}><Reveal><p className={styles.eyebrow}>LE MESSAGE AVANT L’EFFET</p><h2>Ce qui doit rester.<br /><span>Ce qui doit bouger.</span></h2></Reveal><div><p>Une animation utile rend une idée plus facile à suivre. Le brief définit le public, le message central, l’action attendue et le support de diffusion. Le rythme, les transitions et la place du texte se décident ensuite.</p><p>Une vidéo explicative peut détailler un parcours. Un format publicitaire concentre son propos sur une offre. Une présentation de marque cherche une cohérence visuelle et narrative. Chaque usage demande un cadrage différent.</p><Link href="/publicite" className={styles.link}>Préparer la diffusion publicitaire ↗</Link></div></div></section>
    <section className={styles.formats}><div className="container"><p className={styles.eyebrow}>DES FORMATS POUR DES USAGES</p>{[["Expliquer", "Vidéos de présentation, démonstrations et parcours : rendre un fonctionnement lisible."],["Diffuser", "Déclinaisons publicitaires et sociales : adapter cadrage, lecture et message au support."],["Animer", "Identité de marque et interfaces : préparer des mouvements cohérents avec les éléments disponibles."]].map(([name,text],i) => <Reveal key={name}><div className={styles.format}><span aria-hidden="true">0{i+1}</span><h2>{name}.</h2><p>{text}</p></div></Reveal>)}</div></section>
    <section className={styles.story}><div className={`container ${styles.split}`}><div><p className={styles.eyebrow}>DU BRIEF À LA LIVRAISON</p><h2>Une narration.<br /><span>Des validations.</span></h2><Link href="/ressources" className={styles.link}>Explorer les ressources CODE-V ↗</Link><Link href="/solutions" className={styles.link}>Relier la vidéo aux autres solutions ↗</Link></div><div><ol className={styles.steps}><li><strong>Cadrer</strong><p>Message, public, supports et matière visuelle.</p></li><li><strong>Composer</strong><p>Intention narrative, montage ou animation dans le périmètre retenu.</p></li><li><strong>Valider</strong><p>Étapes de relecture et ajustements convenus.</p></li><li><strong>Décliner</strong><p>Formats et fichiers de livraison adaptés à la diffusion prévue.</p></li></ol><p>Durée, complexité et nombre de versions sont précisés au devis. Voix off, musique, licences et moyens de production se cadrent selon le projet. Le budget de diffusion est traité séparément.</p></div></div></section>
    <section className={styles.final}><div className="container"><h2>Que voulez-vous<br /><em>rendre plus clair ?</em></h2><p>Partagez votre message, vos supports et les visuels dont vous disposez. Nous préciserons le format et les moyens de production adaptés.</p><Link href="/contact?service=video-motion" className="button button-primary">Parler de votre vidéo ↗</Link></div></section>
  </div>;
}
