import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
import { getPageBreadcrumb } from "@/data/breadcrumbs";
import styles from "../mentions-legales/legal.module.css";
const title = "Politique de confidentialité — CODE-V";
const description = "Comprendre les données traitées sur CODE-V : formulaire, emails, assistant IA, mesures de fréquentation et de performance, et exercice de vos droits.";
export const metadata: Metadata = { title, description, alternates: { canonical: "https://www.code-v.fr/politique-confidentialite" }, robots: { index: false, follow: true }, openGraph: { title, description, url: "https://www.code-v.fr/politique-confidentialite", type: "website", locale: "fr_FR" } };
export default function PrivacyPage() {
 return <><header className={styles.hero}><div className="container"><Breadcrumb {...getPageBreadcrumb("/politique-confidentialite")} /><h1>Politique de confidentialité</h1><p>Ce qui est traité lorsque vous naviguez sur CODE-V, nous contactez ou utilisez l’assistant.</p></div></header><div className={styles.body}>
 <section><h2>Responsable du traitement et contact</h2><p>Adrien Weissenbacher, entrepreneur individuel exerçant sous le nom commercial CODE-V, est responsable des traitements mis en œuvre pour ce site.</p><address>142 rue de Rivoli<br />75001 Paris<br />France</address><p>Pour toute question ou demande relative à vos données sur ce site, écrivez à <a href="mailto:contact@code-v.fr">contact@code-v.fr</a>. Les coordonnées du site figurent également dans les <Link href="/mentions-legales">mentions légales</Link>.</p></section>
 <section><h2>Formulaire et échanges par email</h2><p>Le formulaire demande votre nom, votre adresse email et votre message. Vous pouvez aussi renseigner votre entreprise et le type de projet. La page d’origine et le service sélectionné sont transmis pour orienter la demande.</p><p>Ces informations servent à recevoir votre demande, vous répondre et préparer l’échange relatif à votre projet. Les champs obligatoires sont nécessaires à l’envoi du formulaire ; les autres peuvent rester vides.</p><p>Resend assure l’envoi d’un email à CODE-V et d’une confirmation à l’adresse que vous fournissez. Votre demande peut ainsi être présente dans les messageries des destinataires et dans les systèmes du prestataire d’envoi. Elle n’est pas envoyée aux outils Analytics comme contenu de conversion.</p></section>
 <section><h2>Assistant IA</h2><p>Lorsque vous envoyez un message, son contenu et un historique récent de la conversation sont transmis par le serveur CODE-V à l’API OpenAI pour produire une réponse. Un message peut donc contenir des données personnelles si vous choisissez d’en communiquer.</p><p>Les conversations sont conservées en mémoire dans l’interface pendant son utilisation. Le site ne dispose pas d’une base de conversations enregistrées ni d’un historique persistant dans le navigateur. Le traitement effectué par le prestataire IA est distinct de cette mémoire locale.</p><p>Évitez de transmettre des informations sensibles, confidentielles ou concernant des tiers. Les événements de mesure de l’assistant portent sur son ouverture et son intent, jamais sur les messages ou réponses.</p></section>
 <section><h2>Fréquentation et performance</h2><p>Vercel Web Analytics mesure la consultation du site et des actions comme un clic commercial ou un formulaire confirmé. Les propriétés ajoutées par CODE-V sont limitées à des chemins de pages et des identifiants contrôlés de services, articles ou projets. Elles ne contiennent pas les champs du formulaire, les messages du chatbot, les numéros de téléphone ou les adresses email.</p><p>Vercel Speed Insights mesure les performances d’affichage et d’interaction. Les mesures peuvent inclure la page, le navigateur, le type d’appareil, le réseau et des informations techniques de performance.</p><p>Vercel présente Web Analytics comme une mesure sans cookies. Aucun GA4, pixel publicitaire ou stockage d’attribution supplémentaire n’est installé dans le code de ce site.</p><p><a href="https://vercel.com/docs/analytics/privacy-policy">Confidentialité de Web Analytics</a> · <a href="https://vercel.com/docs/speed-insights/privacy-policy">Confidentialité de Speed Insights</a></p></section>
 <section><h2>Publications, médias et polices</h2><p>Les publications Facebook publiques de CODE-V sont récupérées côté serveur. Aucun compte Facebook ni donnée privée du visiteur n’est demandé par le fil. Lorsqu’une image Facebook est affichée, votre navigateur peut contacter le serveur de médias Meta ; ce chargement implique la transmission des informations techniques nécessaires, notamment votre adresse IP.</p><p>Les polices du site sont chargées depuis Google Fonts : votre navigateur contacte les serveurs correspondants. Les liens vers Facebook, Google ou les sites clients vous conduisent vers des services régis par leurs propres politiques.</p></section>
 <section><h2>Services techniques et transferts</h2><p>Vercel fournit l’hébergement et les outils de mesure, Resend l’envoi des emails et OpenAI la génération des réponses de l’assistant. Ces prestataires peuvent traiter des données dans des pays situés hors de l’Espace économique européen, selon leurs infrastructures et conditions applicables.</p><p>Leurs documents décrivent les traitements et mécanismes de protection proposés.</p><ul><li><a href="https://vercel.com/legal/dpa">Accord de traitement Vercel</a></li><li><a href="https://resend.com/legal/dpa">Accord de traitement Resend</a></li><li><a href="https://openai.com/policies/privacy-policy/">Politique de confidentialité OpenAI</a></li></ul></section>
 <section><h2>Conservation et sécurité</h2><p>Le rechargement de l’interface met fin à son historique local de conversation. Les emails envoyés et les données traitées par les prestataires ne sont pas supprimés par cette action. Pour une demande d’accès ou d’effacement relative à vos échanges avec CODE-V, utilisez le contact indiqué ci-dessus.</p><p>Le site utilise HTTPS. Les clés des services d’envoi, du chatbot et de Facebook sont utilisées côté serveur. Ces mesures réduisent l’exposition des accès techniques ; elles ne rendent pas une transmission de données exempte de tout risque.</p></section>
 <section><h2>Vos droits</h2><p>Selon les conditions prévues par la réglementation, vous pouvez demander l’accès, la rectification, l’effacement ou la limitation du traitement de vos données, ainsi que vous opposer à certains traitements ou demander leur portabilité lorsqu’elle s’applique.</p><p>Adressez votre demande à <a href="mailto:contact@code-v.fr">contact@code-v.fr</a>, en précisant les échanges concernés pour permettre de les retrouver. Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>.</p></section>
 </div></>;
}
